(function(){
  'use strict';

  var roles={
    platform_admin:{label:'平台管理员',surface:'web',org:'优洗通平台',subtitle:'平台业务、资金与基础资料管理',nav:['经营总览','业务订单','退污退款','客户与组织','酒店与楼层','洗涤厂与站点','协议价格','酒店服务关系','司机负责范围','钱包与流水','工厂结算','商城商品','商城订单','用户与权限']},
    platform_ops:{label:'平台运营',surface:'web',org:'优洗通平台',subtitle:'订单、客户、价格、商城与司机范围',nav:['业务订单','退污退款','客户与组织','酒店与楼层','洗涤厂与站点','协议价格','酒店服务关系','司机负责范围','工厂结算','商城商品','商城订单','用户与权限']},
    platform_finance:{label:'平台财务',surface:'web',org:'优洗通平台',subtitle:'经营数据、钱包流水与工厂结算',nav:['经营总览','业务订单','退污退款','客户与组织','酒店与楼层','洗涤厂与站点','协议价格','酒店服务关系','司机负责范围','钱包与流水','工厂结算','商城订单','用户与权限']},
    hotel_admin:{label:'酒店管理员',surface:'mobile',org:'云栖酒店',subtitle:'补充、订单、账户、商城与员工',nav:['补充','订单','商城','我的']},
    hotel_operator:{label:'酒店操作员',surface:'mobile',org:'云栖酒店',subtitle:'补充下单、订单与退污、商城',nav:['补充','订单','商城','我的']},
    factory_admin:{label:'工厂管理员',surface:'factory',org:'桐乡洗涤一厂',subtitle:'本厂订单、退款、仓库、结算与报表',nav:['经营总览','业务订单','退污退款','工厂结算','布草与仓库','RFID 扫描记录','业务报表']},
    factory_operator:{label:'工厂操作员',surface:'factory',org:'桐乡洗涤一厂',subtitle:'本厂订单履约、退款确认、仓库与扫描记录',nav:['经营总览','业务订单','退污退款','工厂结算','布草与仓库','RFID 扫描记录','业务报表']},
    factory_finance:{label:'工厂财务',surface:'factory',org:'桐乡洗涤一厂',subtitle:'本厂订单、结算与报表只读',nav:['经营总览','业务订单','工厂结算','业务报表']},
    driver:{label:'司机',surface:'mobile',org:'桐乡洗涤一厂',subtitle:'本人负责区域与酒店清单',nav:['负责酒店']},
    terminal:{label:'厂内终端（工厂操作员）',surface:'terminal',org:'桐乡洗涤一厂',subtitle:'首次芯片入库与租赁备货',nav:['首次芯片入库','租赁备货']}
  };
  var state={role:'platform_ops',section:'业务订单',view:'normal',navCollapsed:false,qty:{'被套':40,'床单':60,'浴巾':20},scan:28,progress:0};
  var terminalDraft={site:'',sku:'',reference:'',rfid:'',quantity:'1'};
  var terminalEvents=[{mode:'首次芯片入库',reference:'IN-20260907-028',quantity:28,time:'今日 10:08'},{mode:'租赁备货',reference:'RP202609060086',quantity:64,time:'昨日 16:26'}];
  var mobileOrderTab='orders';
  var roleSelect=document.getElementById('roleSelect');
  var viewSelect=document.getElementById('viewSelect');
  var root=document.getElementById('prototypeRoot');
  var modal=document.getElementById('prototypeModal');
  var toastTimer=0;

  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch];});}
  function money(value){return '¥'+Number(value).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});}
  function badge(text,tone){return '<span class="status-pill '+(tone||'')+'"><i></i>'+esc(text)+'</span>';}
  function button(text,action,type,disabled){return '<button type="button" class="'+(type||'secondary-button')+'" data-action="'+esc(action)+'"'+(disabled?' disabled':'')+'>'+esc(text)+'</button>';}
  function header(title,desc,actions){return '<div class="screen-head"><div><div class="eyebrow">WORKSPACE</div><h2>'+esc(title)+'</h2><p>'+esc(desc)+'</p></div><div class="screen-actions">'+(actions||'')+'</div></div>';}
  function metric(label,value,note,tone,trend){return '<article class="metric-card"><div class="metric-label"><span>'+esc(label)+'</span><i class="metric-tone '+(tone||'')+'"></i></div><div class="metric-value">'+esc(value)+'</div><div class="metric-foot"><span>'+esc(note)+'</span>'+(trend?'<b class="trend '+tone+'">'+esc(trend)+'</b>':'')+'</div></article>';}
  function sampleNote(){return '';}
  function filters(items){return '<div class="filter-bar">'+items.map(function(item){return item.type==='search'?'<label class="search-control"><span>⌕</span><input aria-label="'+esc(item.label)+'" placeholder="'+esc(item.placeholder)+'"></label>':'<label class="select-control"><span>'+esc(item.label)+'</span><select aria-label="'+esc(item.label)+'">'+(item.label==='订单状态'?['全部状态','待派单','已派单','备货中','配送中','已送达']:item.label==='状态'?['全部状态','待确认','已同意','已驳回']:[item.value]).map(function(option){return '<option>'+esc(option)+'</option>';}).join('')+'</select></label>';}).join('')+'<div class="filter-actions">'+button('重置','resetFilters','text-button')+button('查询','filter','primary-button')+'</div></div>';}
  function table(headers,rows){return '<div class="data-table-wrap"><table class="data-table"><thead><tr>'+headers.map(function(h){return '<th>'+esc(h)+'</th>';}).join('')+'</tr></thead><tbody>'+rows.map(function(row){return '<tr>'+row.map(function(cell){return '<td>'+cell+'</td>';}).join('')+'</tr>';}).join('')+'</tbody></table></div><div class="pagination"><span>共 '+rows.length+' 条记录</span><div><button disabled>‹</button><button class="active">1</button><button disabled>›</button></div></div>';}
  function panel(title,aside,body,cls){return '<article class="panel '+(cls||'')+'"><div class="panel-head"><strong>'+esc(title)+'</strong><span>'+esc(aside||'')+'</span></div><div class="panel-body">'+body+'</div></article>';}
  function timeline(items){return '<div class="timeline">'+items.map(function(item,index){return '<div class="timeline-item '+(item.done?'done':'')+'"><i>'+((item.done||index===0)?'✓':'')+'</i><div><strong>'+esc(item.title)+'</strong><span>'+esc(item.time||'待处理')+'</span></div></div>';}).join('')+'</div>';}
  function navSymbol(name){var symbols={'经营总览':'总','业务订单':'单','退污退款':'退','客户与组织':'客','酒店与楼层':'店','协议价格':'价','酒店服务关系':'映','司机负责范围':'司','钱包与流水':'账','工厂结算':'结','商城商品':'商','商城订单':'购','用户与权限':'权','布草与仓库':'仓','RFID 扫描记录':'芯','业务报表':'报','补充':'补','订单':'单','商城':'商','我的':'我','负责酒店':'店','首次芯片入库':'入','租赁备货':'备'};return symbols[name]||name.slice(0,1);}

  function specialState(title){
    var map={
      empty:{icon:'○',title:'当前条件下暂无数据',desc:'调整筛选条件或清除筛选后再试。',action:'清除筛选'},
      error:{icon:'!',title:'数据加载失败',desc:'当前条件已保留，请检查网络后重试。',action:'重新加载'},
      forbidden:{icon:'×',title:'当前角色无权访问',desc:'该功能不在当前组织与角色的授权范围内。',action:'返回工作台'}
    },item=map[state.view];
    return header(title,'当前页面状态')+'<div class="state-card '+state.view+'"><span class="state-icon">'+item.icon+'</span><h3>'+item.title+'</h3><p>'+item.desc+'</p>'+button(item.action,'restore','primary-button')+'</div>';
  }

  function actualDashboard(role){
    var factory=role.surface==='factory';
    var cards=factory?
      metric('待处理订单','12 单','已派发','warning')+metric('备货中订单','6 单','本厂订单','')+metric('待确认退款','4 单','本厂申请','danger')+metric('工厂应收',money(46320),'已送达订单成本','success'):
      metric('合作酒店','28 家','当前有效酒店','')+metric('待处理订单','3 单','已派单','warning')+metric('待确认退款','8 单','全平台申请','danger')+metric('累计充值',money(286500),'已登记资金流水','success')+metric('累计消费',money(214680),'补充与商城扣款','')+metric('工厂应付',money(126320),'已派单至已送达订单成本','warning');
    return header(factory?'洗涤厂生产总览':'平台经营总览',role.org+' · 数据以服务端最新业务账本为准',button('刷新数据','filter','secondary-button'))+'<section class="metric-grid">'+cards+'</section>'+panel('待关注事项','业务列表为准','<div class="state-card"><span class="state-icon">i</span><h3>异常提醒尚未启用</h3><p>请进入订单、退款和资金流水列表查看当前业务记录。</p></div>','chart-panel');
  }

  function actualOrders(role){
    var factory=role.surface==='factory',canOperate=state.role==='factory_admin'||state.role==='factory_operator',canDispatch=state.role==='platform_admin'||state.role==='platform_ops';
    var platformRows=[
      ['<strong>RP202609070018</strong>','云栖酒店','8F','120',money(706),money(486),money(220),'桐乡洗涤一厂',badge('已派单',''),'2026-09-07 09:42','—'],
      ['<strong>RP202609070012</strong>','悦澜酒店','5F','86',money(528),money(362),money(166),'—',badge('待派单','warning'),'2026-09-07 08:16',canDispatch?'<button class="link-button" data-action="dispatchOrder">派单</button>':'—'],
      ['<strong>RP202609060086</strong>','栖岸酒店','3F','64',money(398),money(276),money(122),'桐乡洗涤一厂',badge('已送达','success'),'2026-09-06 16:20','—']
    ];
    var factoryRows=[
      ['<strong>RP202609070018</strong>','云栖酒店','8F','120',money(486),badge(state.progress>2?'已送达':state.progress>1?'配送中':state.progress>0?'备货中':'已派单',state.progress>2?'success':'warning'),'2026-09-07 09:42',canOperate&&state.progress<3?'<button class="link-button" data-action="orderDetail">更新进度</button>':'—'],
      ['<strong>RP202609060086</strong>','栖岸酒店','3F','64',money(276),badge('已送达','success'),'2026-09-06 16:20','—']
    ];
    return header('业务订单',factory?'查看承接订单并按已派单、备货中、配送中、已送达的顺序更新进度；页面只显示工厂结算金额。':'核对酒店补充订单、自动派单结果、酒店扣款、工厂结算和平台毛利。',button('刷新','filter','secondary-button'))+filters([{label:'订单状态',value:'全部状态'}])+panel(factory?'本厂履约订单':'平台订单','每页 20 条',table(factory?['订单号','酒店','所属楼层','布草件数','工厂结算','状态','下单时间','操作']:['订单号','酒店','所属楼层','布草件数','酒店扣款','工厂结算','平台毛利','承接洗涤厂','状态','下单时间','操作'],factory?factoryRows:platformRows));
  }

  function actualRefunds(role){
    var factory=role.surface==='factory',canConfirm=state.role==='factory_admin'||state.role==='factory_operator';
    var rows=factory?[
      ['<strong>RF202609070006</strong>','RP202609060086','栖岸酒店','12','8','明显污渍',badge('已同意','success'),'—'],
      ['<strong>RF202609070003</strong>','RP202609050061','云栖酒店','5','—','不可使用',badge('待确认','warning'),canConfirm?'<button class="link-button" data-action="refundDetail">同意 / 驳回</button>':'—']
    ]:[
      ['<strong>RF202609070006</strong>','RP202609060086','栖岸酒店','12','8',money(33.6),money(22.4),'明显污渍',badge('已同意','success')],
      ['<strong>RF202609070003</strong>','RP202609050061','云栖酒店','5','—',money(40),money(0),'不可使用',badge('待确认','warning')]
    ];
    return header('退污退款',factory?'核对本厂收到的退污申请，可全部、部分同意或驳回；同意后款项退回酒店预付余额。':'查看酒店退污申请、工厂确认数量与退款结果；平台角色仅查看。',button('刷新','filter','secondary-button'))+filters([{label:'状态',value:'全部状态'}])+panel('退款申请','每页 20 条',table(factory?['退款单号','原订单号','酒店','申请件数','确认件数','原因','状态','确认']:['退款单号','原订单号','酒店','申请件数','确认件数','申请退款','实际退款','原因','状态'],rows));
  }

  function actualResource(section,role){
    var platformWriter=state.role==='platform_admin'||state.role==='platform_ops';
    if(section==='协议价格')return header('酒店与工厂价格','按酒店、洗涤厂和布草品类查询两套价格；历史订单继续使用下单时价格。',platformWriter?button('设置价格','createPrice','primary-button'):'')+filters([{type:'search',label:'酒店组织编号',placeholder:'请输入酒店组织编号'},{type:'search',label:'工厂组织编号',placeholder:'请输入工厂组织编号'}])+panel('价格表','',table(['布草编号','布草品类','单位','酒店协议价','工厂成本价'],[['linen-duvet','被套','件',money(8),money(5.5)],['linen-sheet','床单','件',money(5.5),money(3.8)],['linen-towel','浴巾','件',money(2.8),money(1.9)]]));
    if(section==='钱包与流水')return header(section,'按酒店查询不可修改的充值、消费和退款流水。',button('登记充值','recharge','primary-button'))+filters([{type:'search',label:'酒店组织编号',placeholder:'请输入酒店组织编号'}])+panel('资金流水','',table(['流水类型','变动金额','变动后余额','关联业务','摘要','发生时间'],[['布草订单扣款','-'+money(706),money(12680),'RP202609070018','布草补充单','2026-09-07 09:42'],['线下充值','+'+money(20000),money(13386),'BANK-20260901-01','已核验到账','2026-09-01 10:06']]));
    if(section==='工厂结算')return header(section,'按已送达订单中的工厂成本汇总各洗涤厂结算金额。',button('刷新','filter','secondary-button'))+panel('结算汇总','线下结算',table(['工厂组织编号','洗涤厂','已送达订单','结算金额'],[['org-factory-1','桐乡洗涤一厂','128',money(126320)]]));
    if(section==='商城商品')return header(section,'维护酒店耗材商品、统一售价和可售库存。',platformWriter?button('新增商品','createProduct','primary-button'):'')+panel('商品列表','',table(['商品名称','分类','商品说明','统一售价','可售库存','状态'],[['客房高效清洁剂','客房清洁','500ml，温和低泡',money(39),'86',badge('正常','success')],['酒店香氛补充装','香氛用品','清新木质调',money(68),'0',badge('正常','success')]]));
    if(section==='商城订单')return header(section,'查看商城订单金额、商品明细和库存扣减后的订单状态。',button('刷新','filter','secondary-button'))+panel('商城订单','每页 20 条',table(['商城订单号','商品明细','商品件数','订单金额','状态','下单时间'],[['SO202609070006','客房高效清洁剂 × 2','2',money(78),badge('已创建',''),'2026-09-07 10:12']]));
    if(section==='布草与仓库')return header(section,'按首次芯片入库和租赁备货事件汇总本工厂布草数量。',button('刷新','filter','secondary-button'))+panel('仓库汇总','',table(['布草编号','布草品类','累计入库','累计备货','当前可用'],[['linen-duvet','被套','8642','7356','1286'],['linen-sheet','床单','7906','6920','986'],['linen-towel','浴巾','5672','5486','186']]));
    if(section==='RFID 扫描记录')return header(section,'查看厂内终端已提交并由系统确认的扫描事件。',button('刷新','filter','secondary-button'))+panel('扫描事件','每页 20 条',table(['事件编号','工作模式','关联业务','布草品类','识别数量','采集方式','提交时间'],[['evt-20260907-028','首次芯片入库','IN-20260907-028','被套','42','MANUAL','2026-09-07 08:58'],['evt-20260907-019','租赁备货','RP202609070018','床单','60','MANUAL','2026-09-07 10:08']]));
    if(section==='业务报表')return header(section,'查看本工厂累计订单、已送达订单、布草总件数和工厂应收。',button('刷新','filter','secondary-button'))+panel('工厂履约汇总','',table(['累计订单','已送达订单','布草总件数','工厂应收'],[['196','128','8268',money(126320)]]));
    return specialState(section);
  }

  // Shared in-memory identity fixtures. Refreshing restores the demonstration data.
  var identity={orgs:[
    {id:'org-platform',name:'优洗通平台',type:'platform'},
    {id:'org-hotel-yunqi',name:'云栖酒店',type:'hotel',site:'云栖酒店站点',area:'城东片区',address:'桐乡市振兴路 18 号',floors:'1F、2F、3F、8F'},
    {id:'org-factory-1',name:'桐乡洗涤一厂',type:'factory',site:'东区站',area:'城东片区',address:'桐乡市工业园路 20 号'},
    {id:'org-hotel-full',name:'悦澜酒店（账号已满样例）',type:'hotel',site:'悦澜酒店站点',area:'城西片区',address:'桐乡市庆丰路 8 号',floors:'1F、2F'},
    {id:'org-factory-legacy',name:'洗涤二厂（待补管理员）',type:'factory',site:'北区站',area:'城北片区',address:'桐乡市环城北路 10 号'}
  ],users:[],query:{q:'',org:'',role:'',status:'',type:''},page:1,detail:'',draft:null,audit:[],next:100};
  var identityTypes={platform:'平台',hotel:'酒店',factory:'洗涤厂'};
  var identityRoleTypes={platform:['platform_admin','platform_ops','platform_finance','driver'],hotel:['hotel_admin','hotel_operator'],factory:['factory_admin','factory_operator','factory_finance','driver']};
  var identityCapabilities={platform_admin:'组织、全部账号、运营配置和财务管理',platform_ops:'组织、非平台角色账号、派单和业务配置；不办理财务充值',platform_finance:'充值、资金流水和财务工作台；组织与账号只读',hotel_admin:'本酒店成员、补货、退款、商城与酒店业务查询',hotel_operator:'本酒店补货、退款、商城与酒店业务查询；无成员管理',factory_admin:'本厂履约、退款确认、库存、终端、结算与报表；不管理账号',factory_operator:'本厂履约、退款确认、库存、终端及业务查询；不管理账号',factory_finance:'本厂订单、结算与报表查询',driver:'查看本人负责区域与酒店'};
  Object.keys(roles).filter(function(r){return r!=='terminal';}).forEach(function(r,i){identity.users.push({id:'user-'+r,org:r.indexOf('hotel_')===0?'org-hotel-yunqi':r.indexOf('factory_')===0||r==='driver'?'org-factory-1':'org-platform',role:r,name:roles[r].label,login:r,active:true,hotels:r==='driver'?['org-hotel-yunqi']:[],area:r==='driver'?'城东片区':'',sessions:1});});
  for(var identityIndex=0;identityIndex<10;identityIndex++)identity.users.push({id:'sample-'+identityIndex,org:'org-hotel-full',role:identityIndex===0?'hotel_admin':'hotel_operator',name:identityIndex===0?'悦澜管理员':'悦澜员工 '+identityIndex,login:'yuelan_'+identityIndex,active:true,hotels:[],sessions:1});
  identity.users.push({id:'sample-disabled',org:'org-hotel-full',role:'hotel_operator',name:'待恢复员工',login:'yuelan_disabled',active:false,hotels:[],sessions:0});
  identity.users.push({id:'legacy-worker',org:'org-factory-legacy',role:'factory_operator',name:'二厂操作员',login:'legacy_operator',active:true,hotels:[],sessions:1});
  identity.users.forEach(function(u,i){u.createdAt=new Date(Date.UTC(2026,8,1,1,i)).toISOString();});
  function identityCreatedAt(value){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(value));}
  function identityOrg(id){return identity.orgs.find(function(o){return o.id===id;});}
  function identityUser(id){return identity.users.find(function(u){return u.id===id;});}
  function identityWritable(user){return state.role==='platform_admin'||state.role==='platform_ops'&&(!user||user.role.indexOf('platform_')!==0);}
  function identityAssignable(org,user){var values=(identityRoleTypes[(identityOrg(org)||{}).type]||[]).filter(function(r){return state.role==='platform_admin'||r.indexOf('platform_')!==0;});return user?values.filter(function(r){return (r==='driver')===(user.role==='driver');}):values;}
  function identityAdmins(org){return identity.users.filter(function(u){return u.org===org&&u.active&&u.role===(identityOrg(org).type+'_admin');});}
  function identityCount(org){return identity.users.filter(function(u){return u.org===org&&u.active;}).length;}
  function identityOptions(items,value,empty){return (empty!==undefined?'<option value="">'+esc(empty)+'</option>':'')+items.map(function(item){return '<option value="'+esc(item.id)+'"'+(item.id===value?' selected':'')+'>'+esc(item.name)+'</option>';}).join('');}
  function identitySelect(label,key,items,value,empty){return '<label class="form-row"><span>'+esc(label)+'</span><select data-identity-field="'+key+'" aria-label="'+esc(label)+'">'+identityOptions(items,value,empty)+'</select></label>';}
  function identityInput(label,key,value,extra){return '<label class="form-row"><span>'+esc(label)+'</span><input data-identity-field="'+key+'" aria-label="'+esc(label)+'" value="'+esc(value||'')+'" '+(extra||'')+'></label>';}
  function identityRoleInfo(r){if(!roles[r])return '';return '<div class="identity-role-info"><b>'+esc(roles[r].label)+'</b><span>'+esc(identityCapabilities[r])+'</span><small>使用端：'+(r.indexOf('hotel_')===0||r==='driver'?'移动端':r==='factory_operator'||r==='factory_admin'?'管理工作台、移动端':'管理工作台')+' · 数据范围：'+(r==='driver'?'本人负责区域与酒店':r.indexOf('platform_')===0?'全部组织（按角色限制业务操作）':r.indexOf('hotel_')===0?'所属酒店':'所属洗涤厂')+'</small></div>';}
  function identityPaged(headers,rows){var pages=Math.max(1,Math.ceil(rows.length/20));identity.page=Math.min(identity.page,pages);var pageButtons='';for(var i=1;i<=pages;i++)pageButtons+='<button data-action="identityPage:'+i+'" class="'+(identity.page===i?'active':'')+'">'+i+'</button>';var content=rows.length?table(headers,rows.slice((identity.page-1)*20,identity.page*20)).replace(/<div class="pagination">[\s\S]*$/,''):'<div class="identity-empty"><strong>暂无成员</strong><p>可调整查询条件，或添加组织成员。</p></div>';return content+'<div class="pagination identity-pagination"><span>共 '+rows.length+' 个账号</span><div>'+button('‹','identityPrev','text-button',identity.page===1)+pageButtons+button('›','identityNext','text-button',identity.page===pages)+'</div></div>';}
  function identityFilter(isOrg,orgId){var q=isOrg?identity.orgQueryDraft||identity.orgQuery||{}:identity.queryDraft||identity.query;return '<form class="filter-bar identity-filter" data-filter-scope="'+(isOrg?'organizations':'users')+'">'+identityInput(isOrg?'组织名称':'姓名或登录账号','q',q.q,'placeholder="'+(isOrg?'搜索组织名称':'搜索姓名或登录账号')+'"')+(isOrg?identitySelect('组织类型','type',['hotel','factory','platform'].map(function(t){return{id:t,name:identityTypes[t]};}),q.type,'全部类型'):(!orgId?'<label class="form-row"><span>所属组织</span><input data-identity-field="orgSearch" list="identityFilterOrgs" aria-label="所属组织" placeholder="全部组织" value="'+esc((identityOrg(q.org)||{}).name||'')+'"><datalist id="identityFilterOrgs">'+identity.orgs.map(function(o){return '<option value="'+esc(o.name)+'"></option>';}).join('')+'</datalist></label>':'')+identitySelect('角色','role',Object.keys(identityCapabilities).map(function(r){return{id:r,name:roles[r].label};}),q.role,'全部角色')+identitySelect('账号状态','status',[{id:'enabled',name:'启用'},{id:'disabled',name:'停用'}],q.status,'全部状态'))+'<div class="filter-actions">'+button('查询','identitySearch','primary-button')+button('重置','identityReset','secondary-button')+'</div></form>';}
  function identityMemberRows(users){return users.slice().sort(function(a,b){return b.createdAt.localeCompare(a.createdAt)||a.id.localeCompare(b.id);}).map(function(u){var o=identityOrg(u.org),row=[esc(u.name),esc(u.login),esc(o.name),esc(identityTypes[o.type]),esc(identityCreatedAt(u.createdAt)),'<button class="link-button" data-action="identityRole:'+u.role+'">'+esc(roles[u.role].label)+'</button>',badge(u.active?'启用':'停用',u.active?'success':'')];if(identityWritable())row.push(identityWritable(u)?button('维护账号','identityEdit:'+u.id,'link-button'):'只读');return row;});}
  function identityUsers(orgId){var headers=['姓名','登录账号','所属组织','组织类型','创建时间','角色与权限','状态'];if(identityWritable())headers.push('操作');return '<section class="identity-workspace">'+header(orgId?'组织成员':'用户与权限','账号归属一个组织、使用一个固定角色；组织决定数据归属，角色决定业务能力。',button('刷新','identityRefresh','secondary-button')+(identityWritable()?button('添加成员','identityAdd'+(orgId?':'+orgId:''),'primary-button'):''))+(!identityWritable()?'<p class="identity-alert">当前角色只读，可查看账号和权限说明</p>':'')+'<div class="identity-card">'+identityFilter(false,orgId)+identityPaged(headers,identityMemberRows(identity.users.filter(function(u){var q=identity.query;return (!q.q||(u.name+' '+u.login).toLowerCase().indexOf(q.q.toLowerCase())>=0)&&(!(orgId||q.org)||u.org===(orgId||q.org))&&(!q.role||u.role===q.role)&&(!q.status||u.active===(q.status==='enabled'));})))+'</div></section>';}
  function identityDrawer(){var o=identityOrg(identity.detail);if(!o)return '';var admins=identityAdmins(o.id);return '<div class="identity-drawer-mask" data-action="identityBackdrop"><section class="identity-drawer" role="dialog" aria-modal="true" aria-label="组织详情"><header><h2>组织详情</h2><button aria-label="关闭组织详情" data-action="identityBack">×</button></header><div class="identity-drawer-body"><dl class="identity-descriptions"><dt>组织编号</dt><dd>'+esc(o.id)+'</dd><dt>状态</dt><dd>'+(o.active===false?'停用':'启用')+'</dd><dt>组织名称</dt><dd>'+esc(o.name)+'</dd><dt>组织类型</dt><dd>'+identityTypes[o.type]+'</dd></dl>'+(o.address?'<p>'+esc(o.area)+' · '+esc(o.address)+'</p>'+button(o.type==='hotel'?'酒店与楼层':'工厂与站点','catDetail:'+o.id,'secondary-button'):'')+'<p>启用管理员：'+(admins.map(function(u){return esc(u.name)+'（'+esc(u.login)+'）';}).join('、')||'暂无')+'</p>'+(!admins.length?'<p class="identity-alert warning">此组织缺少启用管理员，请补齐管理员</p>'+(identityWritable()&&(o.type!=='platform'||state.role==='platform_admin')?button('补齐管理员','identityAdmin:'+o.id,'primary-button'):''):'')+identityUsers(o.id)+'</div></section></div>';}
  function identityRender(section){
    if(section==='用户与权限')return identityUsers();
    if(section==='客户与组织'){var q=identity.orgQuery||{},rows=identity.orgs.filter(function(o){return (!q.q||o.name.toLowerCase().indexOf(q.q.toLowerCase())>=0)&&(!q.type||o.type===q.type);}).sort(function(a,b){for(var key of ['type','name','id']){if(a[key]!==b[key])return a[key]<b[key]?-1:1;}return 0;}).map(function(o){return [button(o.name,'identityOrg:'+o.id,'link-button')+'<span class="cell-sub">'+esc(o.id)+'</span>',identityTypes[o.type],badge(o.active===false?'停用':'启用',o.active===false?'':'success'),button('详情与成员','identityOrg:'+o.id,'link-button')];});return '<section class="identity-workspace">'+header(section,'集中管理酒店、洗涤厂及其管理员和成员。新组织建档时同步创建首个管理员。',button('刷新','identityRefresh','secondary-button')+(identityWritable()?button('新建组织','identityHotel','primary-button'):''))+'<div class="identity-card">'+identityFilter(true)+(rows.length?table(['组织名称 / 编号','组织类型','状态','操作'],rows).replace(/<div class="pagination">[\s\S]*$/,''):'<div class="identity-empty">暂无组织</div>')+'</div></section>'+identityDrawer();}
    if(section==='司机负责范围')return header(section,'所属组织与负责酒店分别管理；新建司机至少分配一家酒店。',identityWritable()?button('新增司机','identityDriver','primary-button'):'')+panel('司机账号','与用户清单共享数据',table(['司机','账号','所属组织','负责区域','负责酒店','状态','操作'],identity.users.filter(function(u){return u.role==='driver';}).map(function(u){return [esc(u.name),esc(u.login),esc(identityOrg(u.org).name),esc(u.area),u.hotels.map(function(id){return esc(identityOrg(id).name);}).join('、'),badge(u.active?'启用':'停用',u.active?'success':''),identityWritable(u)?button('维护','identityEdit:'+u.id,'link-button'):'只读'];})));
    return null;
  }
  function identityOpenMember(org,user,role,adminOnly){if(!identityWritable(user)){showToast('当前角色只能查看');return;}identity.draft={kind:'member',id:user?user.id:'',org:org||'',locked:!!org,adminOnly:!!adminOnly,driverOnly:role==='driver',name:user?user.name:'',login:user?user.login:'',role:user?user.role:role||'',active:user?user.active:true,hotels:user?user.hotels.slice():[],area:user?user.area:'',password:'',confirmation:''};identityDrawMember();}
  function identityRestriction(u){if(!u)return '';if(u.id==='user-'+state.role)return '不能停用自己或降低自己的管理员角色';if(u.active&&u.role.endsWith('_admin')&&identityAdmins(u.org).length===1)return '组织最后一个启用管理员不能停用或降级';return '';}
  function identityPasswords(label){return formRow(label,'').replaceAll('确认初始密码','确认密码').replace('请再次输入初始密码','请再次输入密码');}
  function identityDrawMember(){var d=identity.draft,u=d.id?identityUser(d.id):null,valid=identityAssignable(d.org,u),restriction=identityRestriction(u);d.mode=d.mode||'edit';if(d.driverOnly)valid=valid.filter(function(r){return r==='driver';});if(d.adminOnly)valid=valid.filter(function(r){return r===identityOrg(d.org).type+'_admin';});if(valid.indexOf(d.role)<0)d.role=d.adminOnly||d.driverOnly?valid[0]||'':'';var orgField=d.locked?identityInput('所属组织','orgLabel',identityOrg(d.org).name,'disabled'):'<label class="form-row"><span>所属组织</span><input data-identity-field="orgSearch" list="identityOrgOptions" aria-label="所属组织" value="'+esc((identityOrg(d.org)||{}).name||'')+'" placeholder="搜索组织名称"><datalist id="identityOrgOptions">'+identity.orgs.filter(function(o){return !d.driverOnly||o.type==='platform'||o.type==='factory';}).map(function(o){return '<option value="'+esc(o.name)+'"></option>';}).join('')+'</datalist></label>';
    var fields=u?identitySelect('维护内容','mode',[{id:'edit',name:'姓名、角色与状态'},{id:'password',name:'重置密码'}],d.mode):'';
    if(d.mode==='edit'){fields+=orgField+identityInput('登录账号','login',d.login,u?'disabled':'autocomplete="off"')+identityInput('姓名','name',d.name,'maxlength="100"')+identitySelect('角色','role',valid.map(function(r){return{id:r,name:roles[r].label};}),d.role,d.adminOnly||d.driverOnly?undefined:'请选择角色')+identityRoleInfo(d.role);
      if(u)fields+=identitySelect('账号状态','active',[{id:'true',name:'启用'},{id:'false',name:'停用'}],String(d.active))+(restriction?'<p class="identity-restriction">'+esc(restriction)+'</p>':'');
      if(!u&&d.role==='driver')fields+='<label class="form-row"><span>负责酒店（业务分配）</span><input data-identity-field="hotelSearch" list="identityHotelOptions" aria-label="负责酒店（业务分配）" placeholder="搜索负责酒店" value="'+esc((identityOrg(d.hotels[0])||{}).name||'')+'"><datalist id="identityHotelOptions">'+identity.orgs.filter(function(o){return o.type==='hotel';}).map(function(o){return '<option value="'+esc(o.name)+'"></option>';}).join('')+'</datalist></label>'+identityInput('负责区域','area',d.area);
    }
    if(!u||d.mode==='password')fields+=identityPasswords(u?'新密码':'初始密码');
    modalShell(u?'维护账号':'添加组织成员','', '<div class="identity-form">'+fields+'</div><p class="identity-error" role="alert"></p>',button('取消','closeModal','secondary-button')+button('保存','identitySave','primary-button'));modal.querySelector('.modal-card').classList.add('identity-dialog');
    var roleSelect=modal.querySelector('[data-identity-field="role"]');if(roleSelect)roleSelect.disabled=!!d.adminOnly||!!d.driverOnly||!d.org||!!(restriction&&u.role.endsWith('_admin'));var disabledOption=modal.querySelector('[data-identity-field="active"] option[value="false"]');if(disabledOption)disabledOption.disabled=!!restriction;
    if(!u||d.mode==='password'){modal.querySelector('[data-create-password]').value=d.password;modal.querySelector('[data-confirm-password]').value=d.confirmation;}}
  function identityCapture(){var d=identity.draft;if(!d)return;modal.querySelectorAll('[data-identity-field]').forEach(function(el){var key=el.dataset.identityField;if(key==='active')d.active=el.value==='true';else if(key==='hotelSearch'){var hotel=identity.orgs.find(function(o){return o.type==='hotel'&&o.name===el.value;});d.hotels=hotel?[hotel.id]:[];}else if(key!=='orgLabel'&&key!=='orgSearch')d[key]=el.value;});var input=modal.querySelector('[data-create-password]');if(input){d.password=input.value;d.confirmation=modal.querySelector('[data-confirm-password]').value;}if(modal.querySelector('.identity-hotels'))d.hotels=Array.from(modal.querySelectorAll('[data-identity-hotel]:checked')).map(function(el){return el.dataset.identityHotel;});}
  function identityError(message){var el=modal.querySelector('.identity-error');if(el)el.textContent=message;else showToast(message);return false;}
  function identityValidate(d,newOrg){var org=newOrg||identityOrg(d.org),u=d.id?identityUser(d.id):null;if(!identityWritable(u))return '当前角色无权维护此账号';if(!org)return '请从列表选择有效组织';if(!d.name.trim()||!d.login.trim())return '姓名和登录账号为必填项';if(identity.users.some(function(item){return item.id!==d.id&&item.login===d.login.trim();}))return '登录账号已存在，请更换';if(!d.role)return '请选择角色';if((identityRoleTypes[org.type]||[]).indexOf(d.role)<0||(state.role!=='platform_admin'&&d.role.indexOf('platform_')===0))return '角色与所属组织或当前管理权限不匹配';if(u&&(u.role==='driver')!==(d.role==='driver'))return '司机与其他角色不能直接转换';if(org.type==='hotel'&&!u&&identityCount(org.id)>=10)return '该酒店已达 10 个启用账号上限，请先停用不再使用的账号';if(!u&&d.role==='driver'&&(!d.area.trim()||!d.hotels.length))return '请填写负责区域，并至少选择一家负责酒店';if(!u){var error=passwordError(d.password);if(error)return error;if(d.password!==d.confirmation)return '两次输入的密码不一致';}if(u&&u.active&&!d.active&&identityRestriction(u))return identityRestriction(u);if(u&&!u.active&&d.active&&org.type==='hotel'&&identityCount(org.id)>=10)return '该酒店已达 10 个启用账号上限，无法恢复';if(u&&u.role!==d.role){if(u.id==='user-'+state.role&&u.role.endsWith('_admin'))return '不能降低自己的管理员角色';if(u.active&&u.role===org.type+'_admin'&&identityAdmins(org.id).length<=1)return '不能降级组织最后一个启用管理员，请先添加其他管理员';}return '';}
  function identityRecord(action,u){identity.audit.push({action:action,user:u.id,time:new Date().toISOString()});}
  function identityCommitMember(){var d=identity.draft,error=identityValidate(d);if(error)return identityError(error);var u=d.id?identityUser(d.id):null;if(u){var changed=u.role!==d.role||u.active!==d.active;u.active=d.active;u.name=d.name.trim();u.role=d.role;u.area=d.area;u.hotels=d.hotels.slice();if(changed)u.sessions=0;identityRecord('修改账号',u);closeModal();render();showToast('账号已保存','success');}else{u={id:'created-'+identity.next++,createdAt:new Date().toISOString(),org:d.org,name:d.name.trim(),login:d.login.trim(),role:d.role,active:true,hotels:d.hotels.slice(),area:d.area,sessions:0};identity.users.push(u);identityRecord('创建账号',u);d.password='';d.confirmation='';closeModal();render();showToast('账号已保存','success');}}
  function identityOpenOrg(type){if(!identityWritable())return;identity.draft={kind:'org',type:type,fixedType:state.section!=='客户与组织',step:1,name:'',site:'',area:'',address:'',floors:'',adminName:'',login:'',password:'',confirmation:'',role:type+'_admin',hotels:[]};identityDrawOrg();}
  function identityDrawOrg(){var d=identity.draft,steps='<ol class="identity-steps">'+['组织资料','首个管理员','确认创建'].map(function(label,i){return '<li class="'+(d.step===i+1?'active':'')+'">'+(i+1)+' · '+label+'</li>';}).join('')+'</ol>',body='';if(d.step===1)body=(d.fixedType?'':identitySelect('组织类型','type',[{id:'hotel',name:'酒店'},{id:'factory',name:'洗涤厂'}],d.type))+identityInput(d.type==='hotel'?'酒店名称':'工厂名称','name',d.name)+(d.type==='factory'?identityInput('首个工厂站点名称','site',d.site):'')+identityInput('所在区域','area',d.area)+identityInput('详细地址','address',d.address);if(d.step===2)body='<p class="identity-alert">创建'+(d.type==='hotel'?'酒店':'工厂')+'管理员，组织与管理员一次保存</p>'+identityInput('管理员姓名','adminName',d.adminName)+identityInput('管理员登录账号','login',d.login)+identityPasswords('初始密码');if(d.step===3)body='<dl class="identity-descriptions single"><dt>组织</dt><dd>'+esc(d.name)+'（'+identityTypes[d.type]+'）</dd>'+(d.type==='factory'?'<dt>首个站点</dt><dd>'+esc(d.site)+'</dd>':'')+'<dt>地址</dt><dd>'+esc(d.area)+' · '+esc(d.address)+'</dd>'+'<dt>管理员</dt><dd>'+esc(d.adminName)+' · '+esc(d.login)+'</dd></dl>';modalShell(d.type==='hotel'?'新建酒店':'新建工厂','',steps+'<div class="identity-form">'+body+'</div><p class="identity-error" role="alert"></p>',button('取消','closeModal','secondary-button')+(d.step>1?button('上一步','identityOrgPrev','secondary-button'):'')+button(d.step===3?'确认创建':'下一步',d.step===3?'identityOrgCommit':'identityOrgNext','primary-button'));modal.querySelector('.modal-card').classList.add('identity-dialog','organization-dialog');if(d.step===2){modal.querySelector('[data-create-password]').value=d.password;modal.querySelector('[data-confirm-password]').value=d.confirmation;}}
  function identityOrgError(){var d=identity.draft;if(!d.name.trim()||(d.type==='factory'&&!d.site.trim())||!d.area.trim()||!d.address.trim())return '请填写完整组织和业务资料';if(identity.orgs.some(function(o){return o.name===d.name.trim();}))return '组织名称已存在，请更换';if(d.step>=2)return identityValidate(Object.assign({},d,{name:d.adminName}),{id:'pending',type:d.type});return '';}
  function identityConfirm(title,desc,action){modalShell(title,'','<p class="dialog-copy">'+esc(desc)+'</p><p class="identity-error" role="alert"></p>',button('取消','identityReturn','secondary-button')+button('确认修改',''+action,'primary-button'));modal.querySelector('.modal-card').classList.add('identity-dialog','identity-confirm');modal.querySelector('.modal-close').dataset.action='identityReturn';}
  function identityHandle(action){
    if(['createHotel','editHotel','createSite','createUser','editUser','editDriver'].indexOf(action)>=0)action={createHotel:'identityHotel',editHotel:'identityHotel',createSite:'identityFactory',createUser:'identityAdd',editUser:'identityAdd',editDriver:'identityDriver'}[action];
    if(action.indexOf('identity')!==0)return false;var parts=action.split(':'),name=parts[0],id=parts[1],d=identity.draft,u=d&&d.id?identityUser(d.id):null;
    if(name==='identityOrg'){identity.detail=id;identity.queryDraft=null;identity.query={q:'',org:'',role:'',status:'',type:''};identity.page=1;state.section='客户与组织';render();}
    if(name==='identityRefresh'){render();}if(name==='identityPage'){identity.page=Number(id);render();}if(name==='identityBack'||name==='identityBackdrop'){identity.detail='';identity.query={q:'',org:'',role:'',status:'',type:''};identity.queryDraft=null;identity.page=1;render();}
    if(name==='identityPrev'||name==='identityNext'){identity.page+=name==='identityNext'?1:-1;render();}
    if(name==='identitySearch'||name==='identityReset'){var scope=identity.detail?root.querySelector('.identity-drawer .identity-filter'):root.querySelector('.identity-filter'),query={q:'',org:'',role:'',status:'',type:''};if(name==='identitySearch'&&scope)scope.querySelectorAll('[data-identity-field]').forEach(function(el){if(el.dataset.identityField==='orgSearch'){var found=identity.orgs.find(function(o){return o.name===el.value;});query.org=found?found.id:el.value?'unknown':'';}else query[el.dataset.identityField]=el.value.trim();});if(scope&&scope.dataset.filterScope==='organizations'){identity.orgQuery=query;identity.orgQueryDraft=null;}else{identity.query=query;identity.queryDraft=null;}identity.page=1;render();}
    if(name==='identityRole'){modalShell('角色权限说明','','<h3>'+esc(roles[id].label)+'</h3>'+identityRoleInfo(id).replace('<b>'+esc(roles[id].label)+'</b>',''),button('关闭','closeModal','secondary-button'));modal.querySelector('.modal-card').classList.add('identity-dialog','identity-explanation');}
    if(name==='identityAdd'||name==='identityAdmin')identityOpenMember(id,null,null,name==='identityAdmin');
    if(name==='identityDriver')identityOpenMember('',null,'driver');
    if(name==='identityEdit'){u=identityUser(id);identityOpenMember(u.org,u);}
    if(name==='identityHotel'||name==='identityFactory')identityOpenOrg(name==='identityHotel'?'hotel':'factory');
    if(name==='identityOrgPrev'){identityCapture();d.step--;identityDrawOrg();}
    if(name==='identityOrgNext'){identityCapture();var oe=identityOrgError();if(oe)identityError(oe);else{d.step++;identityDrawOrg();}}
    if(name==='identityOrgCommit'){var err=identityOrgError();if(err)identityError(err);else{var orgId='org-created-'+identity.next++;identity.orgs.push({id:orgId,name:d.name.trim(),type:d.type,site:d.site.trim(),area:d.area.trim(),address:d.address.trim(),floors:d.floors});var admin={id:'created-'+identity.next++,createdAt:new Date().toISOString(),org:orgId,name:d.adminName.trim(),login:d.login.trim(),role:d.role,active:true,hotels:[],area:'',sessions:0};identity.users.push(admin);identityRecord('建档并创建管理员',admin);d.password='';d.confirmation='';identity.detail=orgId;identity.query={q:'',org:'',role:'',status:'',type:''};identity.queryDraft=null;identity.page=1;state.section='客户与组织';closeModal();render();showToast('组织与首个管理员已创建','success');}}
    if(name==='identitySave'){identityCapture();if(u&&d.mode==='password'){var pe=passwordError(d.password)||(d.password!==d.confirmation?'两次输入的密码不一致':'');if(pe)identityError(pe);else identityConfirm('确认账号维护','账号：'+u.login+'（'+u.name+'）。重置密码。此操作将使该账号所有已登录会话失效，需要重新登录。确认继续？','identityPasswordCommit');}else{var error=identityValidate(d);if(error)identityError(error);else if(u&&(u.role!==d.role||u.active!==d.active))identityConfirm('确认账号维护','账号：'+u.login+'（'+u.name+'）。角色：'+roles[u.role].label+' → '+roles[d.role].label+'；状态：'+(u.active?'启用':'停用')+' → '+(d.active?'启用':'停用')+'。此操作将使该账号所有已登录会话失效，需要重新登录。确认继续？','identitySaveConfirmed');else identityCommitMember();}}
    if(name==='identitySaveConfirmed')identityCommitMember();
    if(name==='identityReturn')identityDrawMember();
    if(name==='identityToggle'){identityCapture();if(!identityWritable(u))identityError('当前角色无权维护');else if(u.active&&u.id==='user-'+state.role)identityError('不能停用自己的账号');else if(u.active&&u.role===identityOrg(u.org).type+'_admin'&&identityAdmins(u.org).length<=1)identityError('不能停用组织最后一个启用管理员，请先添加其他管理员');else if(!u.active&&identityOrg(u.org).type==='hotel'&&identityCount(u.org)>=10)identityError('该酒店已达 10 个启用账号上限，无法恢复');else identityConfirm(u.active?'确认停用账号':'确认恢复账号',u.active?'停用后此账号不可登录，现有会话立即失效。':'恢复后可重新登录，旧会话不会恢复。','identityToggleConfirmed');}
    if(name==='identityToggleConfirmed'){if(!identityWritable(u)||u.active&&u.id==='user-'+state.role||u.active&&u.role===identityOrg(u.org).type+'_admin'&&identityAdmins(u.org).length<=1||!u.active&&identityOrg(u.org).type==='hotel'&&identityCount(u.org)>=10){identityError('当前状态不允许执行，请返回重新检查');return true;}u.active=!u.active;u.sessions=0;identityRecord(u.active?'恢复账号':'停用账号',u);closeModal();render();showToast(u.active?'账号已恢复，需重新登录':'账号已停用，原有会话已失效','success');}
    if(name==='identityPassword'){identityCapture();modalShell('重置账号密码',u.login,formRow('新密码','')+'<p class="dialog-copy">重置后目标账号现有会话立即失效，请安全告知新密码。</p><p class="identity-error" role="alert"></p>',button('返回','identityReturn','secondary-button')+button('重置密码','identityPasswordReview','primary-button'));}
    if(name==='identityPasswordReview'){identityCapture();var pe=passwordError(d.password)||(d.password!==d.confirmation?'两次输入的密码不一致':'');if(pe)identityError(pe);else identityConfirm('确认重置密码','目标账号现有会话立即失效。新密码不再回显，请通过安全渠道告知。','identityPasswordCommit');}
    if(name==='identityPasswordCommit'){if(!identityWritable(u)){identityError('当前角色无权维护');return true;}u.sessions=0;d.password='';d.confirmation='';identityRecord('重置密码',u);closeModal();render();showToast('账号已保存','success');}
    return true;
  }

  function renderWebContent(role){
    var s=state.section;
    if(state.view!=='normal')return specialState(s);
    var identityContent=identityRender(s);if(identityContent!==null)return identityContent;
    if(s==='经营总览')return actualDashboard(role);
    if(s==='业务订单')return actualOrders(role);
    if(s==='退污退款')return actualRefunds(role);
    return actualResource(s,role);
  }

  function renderWeb(role){
    var roleNames={platform_admin:'平台管理员',platform_ops:'平台运营',platform_finance:'平台财务',factory_admin:'工厂管理员',factory_operator:'工厂操作员',factory_finance:'工厂财务'};
    var displayNames={platform_admin:'平台管理员',platform_ops:'平台运营',platform_finance:'平台财务',factory_admin:'洗涤厂管理员',factory_operator:'工厂备货员',factory_finance:'工厂财务'};
    var roleName=roleNames[state.role]||role.label,displayName=displayNames[state.role]||role.label,workspace=role.surface==='factory'?'洗涤厂工作台':'平台工作台';
    return '<div class="web-app '+(state.navCollapsed?'collapsed':'')+'"><aside class="web-sidebar"><div class="web-brand"><span class="brand-block">优</span><span><strong>优洗通</strong><small>运营管理平台</small></span></div><nav class="web-nav"><div class="nav-group-label">工作空间</div>'+role.nav.map(function(item){return '<button class="nav-item '+(item===state.section?'active':'')+'" data-section="'+esc(item)+'" title="'+esc(item)+'"><span class="nav-symbol">'+navSymbol(item)+'</span><span>'+esc(item)+'</span></button>';}).join('')+'</nav><button class="sidebar-collapse" type="button" data-action="collapseNav">'+(state.navCollapsed?'›':'‹ 收起导航')+'</button></aside><section class="web-main"><header class="web-topbar"><div class="admin-header-left"><div class="breadcrumb"><span>'+esc(workspace)+'</span><i>/</i><strong>'+esc(state.section)+'</strong></div></div><div class="admin-header-right"><div class="organization-chip"><span>'+esc(role.org)+'</span><small>'+esc(roleName)+'</small></div><div class="user-menu-wrap"><button class="user-button" type="button" data-action="userMenu" aria-label="用户菜单" aria-expanded="false"><span>'+esc(displayName.slice(0,1))+'</span><i>'+esc(displayName)+'</i><b>⌄</b></button><div class="user-menu" id="webUserMenu"><button type="button" disabled>'+esc(roleName)+'</button><button type="button" data-action="signOut">退出登录</button></div></div></div></header><div class="web-content">'+renderWebContent(role)+'</div></section></div>';
  }

  function mobileHead(role,back){return '<header class="mobile-head '+(back?'simple':'')+'">'+(back?'<button data-action="back" aria-label="返回">‹</button>':'')+'<div><small>优洗通 · '+esc(role.label)+'</small><h1>'+esc(back||role.org)+'</h1></div>'+(back?'<span></span>':'<button class="mobile-record" data-action="mobileRecords">记录</button>')+'</header>';}
  function laundryRow(name,price,quota){var q=state.qty[name]||0;return '<div class="laundry-row"><span class="laundry-icon">'+name.slice(0,1)+'</span><span class="laundry-info"><strong>'+name+'</strong><small>'+money(price)+'/件 · 可补 '+quota+' 件</small></span><span class="stepper"><button data-action="minus" data-item="'+name+'" aria-label="减少'+name+'">−</button><b>'+q+'</b><button data-action="plus" data-item="'+name+'" data-max="'+quota+'" aria-label="增加'+name+'">＋</button></span></div>';}
  function mobileReplenish(role){
    var total=state.qty['被套']*8+state.qty['床单']*5.5+state.qty['浴巾']*2.8,count=state.qty['被套']+state.qty['床单']+state.qty['浴巾'];
    if(state.view!=='normal')return mobileState();
    return '<div class="mobile-gradient"><div class="mobile-brandline"><span><b>优洗通</b><i></i>'+esc(role.org)+'</span><button data-action="mobileRecords">账户记录</button></div><div class="quota-label">可补总量</div><div class="quota-number"><strong>200</strong><span>件</span></div><p>按各品类可补数量分别核算</p><div class="wallet-strip"><span class="wallet-symbol">¥</span><span>余额 <b>'+money(12680)+'</b></span>'+badge('余额充足','lime')+'</div></div><section class="mobile-content"><div class="floor-row"><span><small>当前楼层</small><strong>8F 布草清单</strong></span><button data-action="floor">切换楼层 ›</button></div><div class="laundry-list">'+laundryRow('被套',8,80)+laundryRow('床单',5.5,90)+laundryRow('浴巾',2.8,30)+'</div><div class="rule-hint"><b>下单校验</b><span>提交时校验品类额度、账户余额、当前价格和承接工厂。</span></div></section><footer class="mobile-checkout"><span><small>预计扣款</small><strong>'+money(total)+'</strong><i>'+count+' 件</i></span><button data-action="submitOrder"'+(count===0?' disabled':'')+'>确认下单</button></footer>';
  }

  function mobileOrders(role){
    if(state.view!=='normal')return mobileState();
    var tabs='<div class="mobile-tabs"><button data-action="ordersTab" class="'+(mobileOrderTab==='orders'?'active':'')+'">补充订单</button><button data-action="refundsTab" class="'+(mobileOrderTab==='refunds'?'active':'')+'">退污记录</button></div>';
    if(mobileOrderTab==='refunds')return mobileHead(role,'补充订单')+'<section class="mobile-page">'+tabs+'<div class="order-card"><header><span><strong>RF202609070006</strong><small>关联订单 RP202609060086</small></span>'+badge('已同意','success')+'</header><footer><span><small>通过 8 件</small><b>'+money(22.4)+'</b></span></footer></div><div class="order-card"><header><span><strong>RF202609070003</strong><small>关联订单 RP202609050061</small></span>'+badge('待确认','warning')+'</header><footer><span><small>申请 5 件</small><b>'+money(40)+'</b></span></footer></div></section>';
    return mobileHead(role,'补充订单')+'<section class="mobile-page">'+tabs+'<div class="order-card"><header><span><strong>RP202609070018</strong><small>今日 09:42 · 8F</small></span>'+badge('备货中','warning')+'</header><div class="order-goods"><span>被套 40</span><span>床单 60</span><span>浴巾 20</span></div><footer><span><small>共 120 件</small><b>'+money(706)+'</b></span><button data-action="mobileOrderDetail">查看详情</button></footer></div><div class="order-card"><header><span><strong>RP202609060086</strong><small>昨日 16:20 · 3F</small></span>'+badge('已送达','success')+'</header><div class="order-goods"><span>被套 20</span><span>床单 32</span><span>浴巾 12</span></div><footer><span><small>共 64 件</small><b>'+money(369.6)+'</b></span><button data-action="applyRefund">申请退污</button></footer></div><div class="mini-boundary"><b>退污规则</b><span>仅已送达且仍有可退数量的订单明细可发起；通过后退款至预存账户。</span></div></section>';
  }

  function mobileAccount(role){
    if(state.view!=='normal')return mobileState();
    return mobileHead(role,'账户与账单')+'<section class="mobile-page"><div class="balance-card"><small>可用余额</small><strong>'+money(12680)+'</strong><button data-action="rechargeRequest">充值</button></div><div class="section-title"><strong>账户流水</strong><span>充值、消费与退款分别记账</span></div><div class="mobile-ledger"><div><i>−</i><span><strong>布草订单扣款</strong><small>今日 09:42 · RP202609070018</small></span><b>−¥706.00</b></div><div><i class="plus">+</i><span><strong>退污退款</strong><small>昨日 18:12 · RF202609060012</small></span><b>+¥22.40</b></div><div><i class="plus">+</i><span><strong>线下充值</strong><small>09-01 10:06 · BANK-20260901-01</small></span><b>+¥20,000.00</b></div></div></section>';
  }

  function mobileStore(role){
    if(state.view!=='normal')return mobileState();
    return mobileHead(role,'易耗品商城')+'<section class="mobile-page store-page"><div class="store-search">酒店易耗品</div><div class="product-grid"><article><span class="product-art">清</span><strong>客房高效清洁剂</strong><small>温和低泡 · 库存 86 件</small><div><b>'+money(39)+'</b><button data-action="addCart">＋</button></div></article><article><span class="product-art green">香</span><strong>酒店香氛补充装</strong><small>清新木质调 · 库存 0 件</small><div><b>'+money(68)+'</b><button data-action="soldOut" disabled>售罄</button></div></article></div><button class="cart-float" data-action="cart">提交订单 <b>1</b></button></section>';
  }

  function mobileEmployees(role){
    if(state.view!=='normal')return mobileState();
    return mobileHead(role,'员工账号')+'<section class="mobile-page"><div class="section-title"><strong>员工账号 3</strong><button class="accent-link" data-action="createEmployee">＋ 添加员工</button></div><div class="employee-list"><button type="button" disabled><i>陈</i><span><strong>陈经理</strong><small>hotel_admin · 酒店管理员</small></span>'+badge('正常','success')+'<em>›</em></button><button type="button" disabled><i>周</i><span><strong>周晓</strong><small>hotel_operator_01 · 酒店操作员</small></span>'+badge('正常','success')+'<em>›</em></button><button type="button" disabled><i>王</i><span><strong>王琳</strong><small>hotel_operator_02 · 酒店操作员</small></span>'+badge('停用','')+'<em>›</em></button></div></section>';
  }

  function mobileProfile(role){
    var admin=state.role==='hotel_admin';
    return mobileHead(role,'我的')+'<section class="mobile-page"><div class="profile-card"><i>'+esc(role.label.slice(0,1))+'</i><span><strong>'+esc(role.label)+'</strong><small>'+esc(role.org)+'</small></span>'+badge('当前身份','success')+'</div><div class="menu-list"><button data-action="'+(admin?'openAccount':'denied')+'"><span>账户与账单</span><em>›</em></button><button data-action="'+(admin?'openEmployees':'denied')+'"><span>员工账号</span><em>›</em></button><button data-action="openRefunds"><span>退污记录</span><em>›</em></button></div><button class="danger-button" data-action="signOut">退出登录</button></section>';
  }

  function driverHome(role){
    if(state.view!=='normal')return mobileState();
    return '<div class="driver-hero"><div class="mobile-brandline"><span><b>优洗通</b><i></i>司机工作台</span><button data-action="signOut">退出</button></div><small>司机张师傅</small><h1>本人负责范围</h1><div><span><b>1</b> 个区域</span><span><b>2</b> 家酒店</span></div></div><section class="mobile-page driver-list"><div class="section-title"><strong>城东片区</strong><span>2 家酒店</span></button><button type="button" aria-disabled="true"><i>01</i><span><strong>云栖酒店</strong><small>桐乡市振兴路 18 号 · 服务点：东区站</small></span></div><button type="button" aria-disabled="true"><i>02</i><span><strong>悦澜酒店</strong><small>桐乡市梧桐路 9 号 · 服务点：东区站</small></span></button></section>';
  }

  function mobileState(){
    var map={empty:['○','暂无业务记录','新的记录会显示在这里'],error:['!','加载失败','网络异常，请稍后重试'],forbidden:['×','无权查看','当前角色不具备此功能权限']},item=map[state.view];
    return '<div class="mobile-state"><i>'+item[0]+'</i><strong>'+item[1]+'</strong><span>'+item[2]+'</span><button data-action="restore">'+(state.view==='error'?'重新加载':'返回首页')+'</button></div>';
  }

  function renderMobile(role){
    var content=state.section==='补充'?mobileReplenish(role):state.section==='订单'?mobileOrders(role):state.section==='账户'?mobileAccount(role):state.section==='商城'?mobileStore(role):state.section==='员工'?mobileEmployees(role):state.section==='负责酒店'?driverHome(role):mobileProfile(role);
    var nav=state.role==='driver'?'':'<nav class="mobile-nav">'+role.nav.map(function(item){return '<button class="'+(item===state.section?'active':'')+'" data-section="'+esc(item)+'"><i>'+navSymbol(item)+'</i><span>'+esc(item)+'</span></button>';}).join('')+'</nav>';
    return '<div class="device-stage"><div class="phone-frame"><div class="phone-screen"><div class="mobile-scroll">'+content+'</div>'+nav+'</div></div><div class="device-caption"><b>'+esc(role.label)+'</b><span>'+(role.label==='司机'?'司机负责范围':'微信小程序')+'</span></div></div>';
  }

  function terminalWorkspace(role){
    var inbound=state.section==='首次芯片入库';
    if(state.view!=='normal')return mobileState();
    var fields=[['site','洗涤站点 ID','由后台站点配置提供'],['sku','布草品类 ID','由后台品类配置提供'],['reference','业务引用',inbound?'厂商事件唯一标识，用于防重':'关联本站备货订单或厂商事件号'],['rfid','芯片号',inbound?'由设备适配器写入':'批量计数时可由适配器留空'],['quantity','有效数量','设备本次有效计数']];
    return '<header class="terminal-mobile-head"><div><small>'+esc(role.org)+'</small><h1>终端工位</h1></div><button type="button" data-action="signOut">退出</button></header><section class="terminal-mobile-content"><div class="terminal-mode-switch">'+role.nav.map(function(item){return '<button type="button" class="'+(item===state.section?'active':'')+'" data-section="'+esc(item)+'">'+esc(item)+'</button>';}).join('')+'</div><div class="terminal-mobile-form">'+fields.map(function(field){return '<label><span>'+field[1]+'</span><input data-terminal-field="'+field[0]+'" value="'+esc(terminalDraft[field[0]])+'" placeholder="'+esc(field[2])+'" aria-label="'+field[1]+'"'+(field[0]==='quantity'?' type="number" min="1" step="1"':'')+'></label>';}).join('')+'<button type="button" class="terminal-submit" data-action="terminalSubmit">校验并提交事件</button></div><div class="terminal-history-title"><strong>最近事件</strong><span>当前工厂</span></div><div class="terminal-events">'+terminalEvents.map(function(item){return '<article><div><strong>'+esc(item.mode)+'</strong><small>'+esc(item.reference)+' · '+esc(item.time)+'</small></div><span>'+badge('有效 '+item.quantity,'success')+badge('MANUAL','')+'</span></article>';}).join('')+'</div></section>';
  }

  function submitTerminal(){
    var quantity=Number(terminalDraft.quantity);
    if(!terminalDraft.site.trim()||!terminalDraft.sku.trim()||!terminalDraft.reference.trim()||!Number.isInteger(quantity)||quantity<1){showToast('请完整输入事件数据，有效数量须为正整数');return;}
    if(state.section==='首次芯片入库'&&!terminalDraft.rfid.trim()){showToast('首次入库必须提供芯片号');return;}
    terminalEvents.unshift({mode:state.section,reference:terminalDraft.reference.trim(),quantity:quantity,time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})});
    terminalDraft.reference='';terminalDraft.rfid='';terminalDraft.quantity='1';render();showToast('设备事件已提交','success');
  }

  function renderTerminal(role){
    return '<div class="device-stage"><div class="phone-frame terminal-phone"><div class="phone-screen"><div class="terminal-mobile-scroll">'+terminalWorkspace(role)+'</div></div></div><div class="device-caption"><b>厂内终端</b><span>非微信构建 · 竖屏工位</span></div></div>';
  }

  function modalShell(title,kicker,content,footer,wide){
    modal.innerHTML='<section class="modal-card '+(wide?'wide':'')+'" role="dialog" aria-modal="true" aria-labelledby="modalTitle"><header><span><small>'+esc(kicker||'BUSINESS ACTION')+'</small><h2 id="modalTitle">'+esc(title)+'</h2></span><button class="modal-close" data-action="closeModal" aria-label="关闭">×</button></header><div class="modal-content">'+content+'</div><footer>'+(footer||button('关闭','closeModal','secondary-button'))+'</footer></section>';
    modal.classList.add('show');modal.setAttribute('aria-hidden','false');var close=modal.querySelector('.modal-close');if(close)close.focus();
  }
  function closeModal(){modal.classList.remove('show');modal.setAttribute('aria-hidden','true');modal.innerHTML='';}
  function passwordError(value){
    if(!value)return '请输入初始密码';
    if(value.length<8||value.length>20)return '密码须为 8～20 位';
    if(!/^[!-~]+$/.test(value))return '密码仅支持英文半角字符，不允许空格、中文或其他非英文字符';
    if(Number(/[A-Za-z]/.test(value))+Number(/[0-9]/.test(value))+Number(/[^A-Za-z0-9]/.test(value))<2)return '字母、数字、特殊字符至少包含两种';
    return '';
  }
  function formRow(label,value,help){
    if(/密码/.test(label))return '<div class="password-fields"><label class="form-row"><span>'+esc(label)+'</span><input data-create-password aria-label="'+esc(label)+'" type="password" autocomplete="new-password" value="" placeholder="8～20 位，至少包含两种字符"><small>英文字母、数字、特殊字符至少包含两种；仅支持英文半角字符，不允许空格或中文。</small></label><label class="form-row"><span>确认初始密码</span><input data-confirm-password aria-label="确认初始密码" type="password" autocomplete="new-password" value="" placeholder="请再次输入初始密码"></label><button type="button" class="text-button" data-action="toggleCreatePassword" aria-pressed="false">显示密码</button><p class="password-error" role="alert" aria-live="polite"></p></div>';
    return '<label class="form-row"><span>'+esc(label)+'</span><input aria-label="'+esc(label)+'"'+(/（分）|库存/.test(label)?' type="number" min="0" step="1"':'')+' value="'+esc(value||'')+'">'+(help?'<small>'+esc(help)+'</small>':'')+'</label>';
  }
  function showConfigForm(action){
    var originalAction=action,aliases={editHotel:'createHotel',editPrice:'createPrice',editProduct:'createProduct',editUser:'createUser',editEmployee:'createEmployee'};action=aliases[action]||action;
    var config={
      createPrice:{title:'设置当前布草价格',kicker:'酒店与工厂价格',content:'<div class="form-grid">'+formRow('价格类型','酒店协议价')+formRow('酒店组织编号','org-hotel-yunqi')+formRow('工厂组织编号','org-factory-1')+formRow('布草品类编号','linen-duvet')+formRow('单价（分）','800')+'</div><div class="boundary-banner"><strong>历史订单</strong><span>修改当前价格不改写已生成订单的价格。</span></div>'},
      createProduct:{title:'新增商城商品',kicker:'商城商品',content:'<div class="form-grid">'+formRow('商品名称','客房高效清洁剂')+formRow('商品分类','客房清洁')+formRow('统一售价（分）','3900')+formRow('初始库存','86')+'</div>'+formRow('商品说明','温和低泡 · 500ml')+formRow('商品图片地址','')},
      createEmployee:{title:'添加酒店员工',kicker:'员工账号',content:'<div class="form-grid">'+formRow('姓名','周晓')+formRow('登录账号','hotel_operator_02')+formRow('初始密码','********')+'</div><p class="dialog-copy">新增账号角色为酒店操作员。</p>'}
      ,warehouseEdit:{title:'维护仓库货架',kicker:'库存位置',content:'<div class="form-grid">'+formRow('洗涤站点','东区站')+formRow('仓区 / 货架','A 区 · A-01')+formRow('布草品类','被套')+formRow('容量','600 件')+'</div><div class="boundary-banner"><strong>组织隔离</strong><span>只能维护本厂所属站点的仓库和货架。</span></div>'}
    },item=config[action];if(!item)return false;var title=originalAction.indexOf('edit')===0?item.title.replace('新增','编辑').replace('新建','编辑'):item.title;modalShell(title,item.kicker,item.content,button('取消','closeModal','secondary-button')+button(action==='createHotel'?'保存并继续':'保存配置','confirmGeneric','primary-button'),true);return true;
  }
  function showOrderDetail(){
    var role=roles[state.role],factory=role.surface==='factory';
    var nextAction=state.progress===0?'开始备货':state.progress===1?'确认出库':state.progress===2?'确认送达':'履约完成';
    var summary=factory?'<div class="order-summary"><div><small>酒店 / 所属楼层</small><b>云栖酒店 · 8F</b></div><div><small>洗涤站点</small><b>东区站</b></div><div><small>总件数</small><b>120 件</b></div><div><small>当前待办</small><b>'+nextAction+'</b></div></div>':'<div class="order-summary"><div><small>酒店 / 所属楼层</small><b>云栖酒店 · 8F</b></div><div><small>洗涤站点</small><b>东区站</b></div><div><small>总件数</small><b>120 件</b></div><div><small>扣款金额</small><b>'+money(706)+'</b></div></div>';
    var detailTable=factory?table(['品类','数量'],[['被套','40 件'],['床单','60 件'],['浴巾','20 件']]):table(['品类','数量','销售单价','小计'],[['被套','40 件',money(8),money(320)],['床单','60 件',money(5.5),money(330)],['浴巾','20 件',money(2.8),money(56)] ]);
    modalShell('补充订单详情','RP202609070018',summary+'<p class="identity-alert">配送地址：桐乡市振兴路 18 号（下单时快照）</p>'+detailTable+'<h3 class="modal-subtitle">履约状态</h3>'+timeline([{title:'订单已派发',time:'今日 09:42',done:true},{title:'工厂备货中',time:state.progress>0?'今日 10:08':'待处理',done:state.progress>0},{title:'配送中',time:state.progress>1?'今日 10:26':'待处理',done:state.progress>1},{title:'已送达',time:state.progress>2?'今日 11:06':'待处理',done:state.progress>2}]),button('关闭','closeModal','secondary-button')+(factory&&(state.role==='factory_admin'||state.role==='factory_operator')&&state.progress<3?button(nextAction,'advance','primary-button'):''),true);
  }
  function showDispatchOrder(){
    modalShell('派发补充订单','RP202609070012','<div class="order-summary"><div><small>酒店</small><b>悦澜酒店</b></div><div><small>所属楼层</small><b>5F</b></div><div><small>布草件数</small><b>86 件</b></div><div><small>当前状态</small><b>待派单</b></div></div><div class="form-grid">'+formRow('承接洗涤厂组织编号','org-factory-1')+formRow('工厂站点编号','site-factory-center')+'</div>',button('取消','closeModal','secondary-button')+button('确认派单','confirmDispatch','primary-button'));
  }
  function showRefund(){
    var role=roles[state.role],factory=role.surface==='factory',hotel=role.surface==='mobile'&&state.role!=='driver';
    if(!factory&&!hotel){modalShell('退污退款详情','RF202609070003','<div class="detail-grid"><div><small>申请酒店</small><b>云栖酒店</b></div><div><small>关联订单</small><b>RP202609050061</b></div><div><small>申请件数</small><b>5 件</b></div><div><small>当前状态</small><b>待确认</b></div></div>'+formRow('退污原因','不可使用'),button('关闭','closeModal','secondary-button'),true);return;}
    modalShell(factory?'确认退污退款':'发起退污申请','RF202609070003','<div class="pending-banner"><b>退污不换货</b><span>'+(factory?'可全部、部分同意或驳回；同意金额按原订单单价退回酒店预付余额。':'从已送达订单的一条明细申请，并填写退污原因。')+'</span></div><div class="refund-line"><span><strong>被套</strong><small>申请数量 5 件</small></span><label><small>'+(factory?'确认数量':'申请数量')+'</small><input id="refundQuantity" aria-label="'+(factory?'确认数量':'申请数量')+'" type="number" min="1" max="5" step="1" value="5"></label><label><small>上限</small><b>5 件</b></label></div>'+formRow(factory?'核验备注':'退污原因',factory?'部分同意':'明显污渍'),button('取消','closeModal','secondary-button')+(factory?button('驳回申请','rejectRefund','secondary-button'):'')+button(factory?'确认提交':'提交退污申请','confirmRefund','primary-button'));
  }
  function showRecharge(isHotel){
    if(isHotel){modalShell('充值方式待开通','账户充值','<p class="dialog-copy">当前请联系优洗通财务处理授权充值，页面不会直接入账。</p>',button('知道了','closeModal','primary-button'));return;}
    modalShell('登记已核验的线下充值','钱包与流水',formRow('酒店组织编号','org-hotel-yunqi')+formRow('到账金额（分）','2000000')+formRow('银行流水号','BANK-20260907-1826')+formRow('核验备注','线下到账已核验'),button('取消','closeModal','secondary-button')+button('确认登记','confirmRecharge','primary-button'));
  }
  function showGeneric(title,desc){modalShell(title,'操作确认','<div class="dialog-illustration">'+navSymbol(title)+'</div><p class="dialog-copy">'+esc(desc)+'</p>',button('取消','closeModal','secondary-button')+button('确认','confirmGeneric','primary-button'));}
  function showSubmitOrder(){var total=state.qty['被套']*8+state.qty['床单']*5.5+state.qty['浴巾']*2.8,count=state.qty['被套']+state.qty['床单']+state.qty['浴巾'];modalShell('确认补充订单','云栖酒店 · 8F','<div class="confirm-amount"><small>本次预计扣款</small><strong>'+money(total)+'</strong><span>共 '+count+' 件 · 固定分配至东区站</span></div><div class="confirm-list"><p><span>被套 × '+state.qty['被套']+'</span><b>'+money(state.qty['被套']*8)+'</b></p><p><span>床单 × '+state.qty['床单']+'</span><b>'+money(state.qty['床单']*5.5)+'</b></p><p><span>浴巾 × '+state.qty['浴巾']+'</span><b>'+money(state.qty['浴巾']*2.8)+'</b></p></div><div class="check-row"><i>✓</i><span><b>余额充足</b><small>提交时将再次校验额度、余额、价格和站点映射</small></span></div>',button('返回修改','closeModal','secondary-button')+button('确认并扣款','confirmOrder','lime-button'));
  }

  function openForAction(action){
    if(action==='orderDetail'||action==='mobileOrderDetail')return showOrderDetail();
    if(action==='dispatchOrder')return showDispatchOrder();
    if(action==='refundDetail'||action==='applyRefund')return showRefund();
    if(action==='recharge'||action==='confirmRecharge')return showRecharge(false);
    if(action==='rechargeRequest')return showRecharge(true);
    if(action==='submitOrder')return showSubmitOrder();
    if(action==='createMapping')return catMappingDialog('org-hotel-yunqi');
    if(showConfigForm(action))return;
    var info={floor:['切换楼层','切换仅改变所属楼层，保留已选品类和数量。'],otherLaundry:['添加其他布草','仅可添加酒店已配置价格的布草品类。'],cart:['提交商城订单','提交时再次校验商品状态、库存和预存余额。'],driverHotel:['负责酒店','查看当前分配的酒店、地址和服务点。'],roleInfo:['角色与权限','页面按组织和角色隔离信息。'],ledger:['资金流水','每笔资金变动关联业务单号和变动后余额。'],help:['使用帮助','按当前角色展示操作说明。'],about:['关于优洗通','酒店、平台与洗涤厂的布草业务协作平台。']};
    if(info[action])showGeneric(info[action][0],info[action][1]);
  }

    // Catalog demonstration state is persisted separately from account credentials.
  var catalog={floors:[],sites:[],mappings:{'org-hotel-yunqi':'site-factory-east'},orders:[],hotel:'org-hotel-yunqi',selection:{},drafts:{},query:{},detail:'',draft:null,next:1};
  identity.orgs.push({id:'org-hotel-floorless',name:'无楼层演示酒店',type:'hotel',area:'城东片区',address:'桐乡市示例路 6 号',floors:''});
  catalog.mappings['org-hotel-floorless']='site-factory-east';
  identity.orgs.forEach(function(o){o.active=true;o.version=1;if(o.type==='hotel')(o.floors||'').split('、').filter(Boolean).forEach(function(n,i){catalog.floors.push({id:o.id+'-floor-'+i,hotel:o.id,name:n,sort:i+1,active:true,version:1});});if(o.type==='factory')catalog.sites.push({id:o.id==='org-factory-1'?'site-factory-east':'site-factory-north',factory:o.id,name:o.site,area:o.area,address:o.address,active:true,version:1});});
  try{var savedCatalog=JSON.parse(localStorage.getItem('youxitong-catalog-prototype-v3'));if(savedCatalog&&savedCatalog.catalog&&Array.isArray(savedCatalog.orgs)){Object.assign(catalog,savedCatalog.catalog);catalog.query={};catalog.detail='';catalog.draft=null;catalog.drafts=catalog.drafts||{};identity.orgs=savedCatalog.orgs;if(Array.isArray(savedCatalog.users))identity.users=savedCatalog.users;identity.next=savedCatalog.identityNext||100;if(savedCatalog.qty)state.qty=savedCatalog.qty;}}catch(ignore){}
  function catalogSave(){catalog.drafts[catalog.hotel]=Object.assign({},state.qty);try{localStorage.setItem('youxitong-catalog-prototype-v3',JSON.stringify({catalog:catalog,orgs:identity.orgs,users:identity.users,identityNext:identity.next,qty:state.qty}));}catch(ignore){}}
  function catHotel(){return identityOrg(catalog.hotel)||identity.orgs.find(function(o){return o.type==='hotel';});}
  function catFloors(id){return catalog.floors.filter(function(f){return f.hotel===id;}).sort(function(a,b){return a.sort-b.sort||a.name.localeCompare(b.name,'zh-CN');});}
  function catSite(id){return catalog.sites.find(function(s){return s.id===id;});}
  function catRelation(id){var s=catSite(catalog.mappings[id]);return s?identityOrg(s.factory).name+' / '+s.name:'待配置';}
  function catServices(site){return identity.orgs.filter(function(o){return catalog.mappings[o.id]===site;});}
  function catField(label,key,value,type){return '<label class="form-row"><span>'+esc(label)+'</span><input data-cat-field="'+key+'" aria-label="'+esc(label)+'" type="'+(type||'text')+'" value="'+esc(value)+'"></label>';}
  function catSelect(label,key,items,value){return '<label class="form-row"><span>'+esc(label)+'</span><select data-cat-field="'+key+'" aria-label="'+esc(label)+'">'+items.map(function(o){return '<option value="'+esc(o.id)+'"'+(String(o.id)===String(value)?' selected':'')+'>'+esc(o.name)+'</option>';}).join('')+'</select></label>';}
  function catStatus(key,value){return catSelect('状态',key,[{id:'true',name:'启用'},{id:'false',name:'停用'}],String(value));}
  function catCapture(){var d=catalog.draft;modal.querySelectorAll('[data-cat-field]').forEach(function(el){d[el.dataset.catField]=el.value;});return d;}
  function catDialog(title,body,action){identity.draft=null;modalShell(title,'', '<div class="catalog-form">'+body+'</div><p class="identity-error" role="alert"></p>',button('取消','closeModal','secondary-button')+(action&&identityWritable()?button('保存',action,'primary-button'):''),true);}
  function catList(section){var factory=section==='洗涤厂与站点',mapping=section==='酒店服务关系',q=catalog.query,items=identity.orgs.filter(function(o){return o.type===(factory?'factory':'hotel')&&(!q.q||o.name.includes(q.q))&&(!q.status||String(o.active)===q.status)&&(!q.mapping||(q.mapping==='yes')===!!catalog.mappings[o.id]);});
    var controls='<div class="filter-bar catalog-filter">'+catField(factory?'工厂名称':'酒店名称','q',q.q||'')+catSelect('档案状态','status',[{id:'',name:'全部状态'},{id:'true',name:'启用'},{id:'false',name:'停用'}],q.status||'')+(!factory?catSelect('承接关系','mapping',[{id:'',name:'全部'},{id:'yes',name:'已关联站点'},{id:'no',name:'未关联站点'}],q.mapping||''):'')+button('查询','catSearch','primary-button')+button('重置','catReset','secondary-button')+'</div>';
    return header(section,factory?'平台统一维护工厂与多个站点；停用前须调整服务酒店。':mapping?'全部酒店的承接关系。变更仅影响新订单，已有订单承接对象与价格保持不变。':'酒店建档不配置楼层。楼层仅作为选品归属，所有楼层共用商品、价格和额度。',identityWritable()&&!mapping?button(factory?'新建工厂':'新建酒店',factory?'identityFactory':'identityHotel','primary-button'):'')+(!identityWritable()?'<p class="identity-alert">财务只读，可查看档案、楼层及服务关系。</p>':'')+panel(factory?'工厂档案':'酒店档案','演示数据 · 修改保存在本浏览器',controls+table(factory?['工厂名称','状态','站点数','操作']:['酒店名称','酒店地址','状态','启用楼层','承接工厂 / 站点','操作'],items.map(function(o){return factory?[button(o.name,'catDetail:'+o.id,'link-button'),badge(o.active?'启用':'停用',o.active?'success':''),catalog.sites.filter(function(s){return s.factory===o.id;}).length,button('详情与站点','catDetail:'+o.id,'link-button')]:[button(o.name,'catDetail:'+o.id,'link-button'),esc(o.address),badge(o.active?'启用':'停用',o.active?'success':''),catFloors(o.id).filter(function(f){return f.active;}).length,esc(catRelation(o.id)),button('详情','catDetail:'+o.id,'link-button')+(identityWritable()?button(catalog.mappings[o.id]?'更换 / 解除':'设置承接关系','catMapping:'+o.id,'link-button'):'')];})))+(catalog.detail?catDetailView(): '');
  }
  function catDetailView(){var o=identityOrg(catalog.detail);if(!o)return '';var writable=identityWritable(),hotel=o.type==='hotel';return '<div class="identity-drawer-mask"><section class="identity-drawer catalog-drawer" role="dialog" aria-modal="true" aria-label="'+(hotel?'酒店详情':'工厂详情')+'"><header><h2>'+esc(o.name)+'</h2>'+button('关闭','catBack','secondary-button')+'</header><div class="identity-drawer-body"><div class="catalog-toolbar">'+badge(o.active?'启用':'停用',o.active?'success':'')+(writable?button('编辑资料','catEdit:'+o.id,'secondary-button'):'')+button('管理员与成员','identityOrg:'+o.id,'secondary-button')+'</div><p>'+esc(o.area||'')+' · '+esc(o.address||'')+'</p><p class="identity-alert">停用仅停止新业务，已有订单继续履约、查询与退款。</p>'+(hotel?'<h3>承接关系</h3><p>'+esc(catRelation(o.id))+'</p>'+(writable?button('配置承接关系','catMapping:'+o.id,'secondary-button'):'')+'<h3>楼层</h3><p>仅维护名称、顺序和状态；不影响商品、价格和额度。</p>'+(writable?button('批量添加楼层','catAddFloors:'+o.id,'primary-button'):'')+table(['楼层名称','顺序','状态','操作'],catFloors(o.id).map(function(f){return[esc(f.name),f.sort,badge(f.active?'启用':'停用',f.active?'success':''),writable?button('编辑 / '+(f.active?'停用':'恢复'),'catFloor:'+f.id,'link-button'):'只读'];})):'<h3>工厂站点</h3>'+(writable?button('新增站点','catAddSite:'+o.id,'primary-button'):'')+table(['站点名称','区域 / 地址','状态','服务酒店','操作'],catalog.sites.filter(function(s){return s.factory===o.id;}).map(function(s){return[esc(s.name),esc(s.area)+'<br>'+esc(s.address),badge(s.active?'启用':'停用',s.active?'success':''),catServices(s.id).map(function(h){return button(h.name,'catDetail:'+h.id,'link-button');}).join('、')||'暂无',writable?button('编辑 / '+(s.active?'停用':'恢复'),'catSite:'+s.id,'link-button'):'只读'];})))+'</div></section></div>';}
  function catMappingDialog(id,dispatch){var h=identityOrg(id),s=catSite(catalog.mappings[id]);catalog.draft={kind:dispatch?'dispatch':'mapping',id:id,version:h.version,factory:s?s.factory:'',site:s?s.id:''};catDrawMapping();}
  function catNameSelect(label,key,items,value){var selected=items.find(function(i){return i.id===value;});return '<label class="form-row"><span>'+label+'</span><input data-cat-name="'+key+'" list="cat-'+key+'" aria-label="'+label+'" placeholder="输入名称搜索选择" value="'+esc(selected?selected.name:'')+'"><datalist id="cat-'+key+'">'+items.map(function(i){return '<option value="'+esc(i.name)+'"></option>';}).join('')+'</datalist></label>';}
  function catDrawMapping(){var d=catalog.draft;catDialog(d.kind==='dispatch'?'派发待派单订单':'配置酒店服务关系', '<p><b>'+esc(identityOrg(d.id).name)+'</b> · 当前：'+esc(catRelation(d.id))+'</p>'+catNameSelect('承接工厂','factory',identity.orgs.filter(function(o){return o.type==='factory'&&o.active;}),d.factory)+catNameSelect('承接站点','site',catalog.sites.filter(function(s){return s.factory===d.factory&&s.active;}),d.site)+'<p class="identity-alert">切换工厂须重新选择站点。仅影响新订单，已有订单保持原承接对象和价格。</p>'+(catalog.mappings[d.id]&&d.kind!=='dispatch'?button('解除承接关系','catRemove','secondary-button'):''),'catMappingReview');}
  function catChanged(o,d){if(o.version!==d.version){identityError('资料已被其他操作修改，请关闭后重新打开。');return true;}return false;}
  function catFinish(message){catalogSave();closeModal();render();showToast(message||'已保存','success');}
  function catHandle(action){if(!/^cat[A-Z]/.test(action))return false;var parts=action.split(':'),a=parts[0],id=parts[1],o=identityOrg(id),d=catalog.draft;
    if(a==='catSearch'){catalog.query={};root.querySelectorAll('.catalog-filter [data-cat-field]').forEach(function(e){catalog.query[e.dataset.catField]=e.value.trim();});render();return true;}
    if(a==='catReset'){catalog.query={};render();return true;}
    if(a==='catDetail'){catalog.detail=id;state.section=o.type==='hotel'?'酒店与楼层':'洗涤厂与站点';render();return true;}
    if(a==='catBack'){catalog.detail='';render();return true;}
    if(a==='catOrder'){catOrderDetail(catalog.orders.find(function(order){return order.id===id;}));return true;}
    if(a==='catFloorPick'){catalog.selection[catHotel().id]=id;catalogSave();closeModal();render();return true;}
    if(a==='catConfirmNoFloor'){catalog.selection[catHotel().id]=null;catalogSave();showSubmitOrder();return true;}
    if(a==='catChooseFloor'){catShowFloors();return true;}
    if(!identityWritable()){showToast('当前角色只读');return true;}
    if(a==='catEdit'){catalog.draft={kind:'org',id:id,version:o.version};catDialog('编辑'+(o.type==='hotel'?'酒店':'工厂')+'资料',catField('名称','name',o.name)+(o.type==='hotel'?catField('区域','area',o.area)+catField('酒店地址','address',o.address):'')+catStatus('active',o.active)+'<p>恢复不会自动恢复已解除的承接关系。</p>','catSaveOrg');}
    if(a==='catSaveOrg'){d=catCapture();o=identityOrg(d.id);if(catChanged(o,d))return true;if(!d.name.trim()||(o.type==='hotel'&&(!d.area.trim()||!d.address.trim()))){identityError('请填写名称、区域和地址');return true;}if(d.active==='false'&&o.type==='factory'&&catalog.sites.some(function(s){return s.factory===o.id&&catServices(s.id).length;})){identityError('工厂仍有服务酒店，请先调整或解除关系');return true;}o.name=d.name.trim();if(o.type==='hotel'){o.area=d.area.trim();o.address=d.address.trim();}o.active=d.active==='true';o.version++;catFinish();}
    if(a==='catAddFloors'){catalog.draft={id:id,version:o.version};catDialog('批量添加楼层','<label class="form-row"><span>楼层名称（逗号或换行分隔）</span><textarea data-cat-field="names" aria-label="楼层名称"></textarea></label><p>同一酒店不可重名，包含停用楼层。新增楼层顺序排在末尾。</p>','catSaveFloors');}
    if(a==='catSaveFloors'){d=catCapture();o=identityOrg(d.id);if(catChanged(o,d))return true;var names=(d.names||'').split(/[、,，\n]/).map(function(n){return n.trim();}).filter(Boolean),seen=catFloors(d.id).map(function(f){return f.name;}),duplicate=[];names.forEach(function(n){if(seen.includes(n))duplicate.push(n);seen.push(n);});if(!names.length||duplicate.length){identityError(duplicate.length?'楼层名称重复：'+duplicate.join('、')+'；停用记录请恢复原楼层。':'请输入至少一个楼层');return true;}var sort=Math.max(0,...catFloors(d.id).map(function(f){return f.sort;}));names.forEach(function(n){catalog.floors.push({id:'floor-new-'+catalog.next++,hotel:d.id,name:n,sort:++sort,active:true,version:1});});o.version++;catFinish();}
    if(a==='catFloor'){var f=catalog.floors.find(function(f){return f.id===id;});catalog.draft={id:id,version:f.version};catDialog('维护楼层',catField('楼层名称','name',f.name)+catField('顺序','sort',f.sort,'number')+catStatus('active',f.active)+'<p>不提供物理删除，停用后可恢复；旧订单归属保持不变。</p>','catSaveFloor');}
    if(a==='catSaveFloor'){d=catCapture();var f=catalog.floors.find(function(f){return f.id===d.id;});if(catChanged(f,d))return true;if(!d.name.trim()||!Number.isSafeInteger(Number(d.sort))||Number(d.sort)<0){identityError('名称必填，顺序须为非负整数');return true;}if(catFloors(f.hotel).some(function(g){return g.id!==f.id&&g.name===d.name.trim();})){identityError('楼层名称重复（包含停用楼层）');return true;}Object.assign(f,{name:d.name.trim(),sort:Number(d.sort),active:d.active==='true',version:f.version+1});catFinish();}
    if(a==='catAddSite'||a==='catSite'){var s=a==='catSite'?catSite(id):null;catalog.draft={id:s?s.id:'',factory:s?s.factory:id,version:s?s.version:0};catDialog(s?'维护工厂站点':'新增工厂站点',catField('站点名称','name',s?s.name:'')+catField('区域','area',s?s.area:'')+catField('站点地址','address',s?s.address:'')+catStatus('active',s?s.active:true),'catSaveSite');}
    if(a==='catSaveSite'){d=catCapture();var s=d.id?catSite(d.id):null;if(s&&catChanged(s,d))return true;if(!d.name.trim()||!d.area.trim()||!d.address.trim()){identityError('名称、区域和地址均为必填项');return true;}if(s&&d.active==='false'&&catServices(s.id).length){identityError('请先调整或解除以下酒店：'+catServices(s.id).map(function(h){return h.name;}).join('、'));return true;}if(!s){s={id:'site-new-'+catalog.next++,factory:d.factory,version:0};catalog.sites.push(s);}Object.assign(s,{name:d.name.trim(),area:d.area.trim(),address:d.address.trim(),active:d.active==='true',version:s.version+1});catFinish();}
    if(a==='catMapping')catMappingDialog(id);
    if(a==='catRemove'||a==='catMappingReview'){if(a==='catMappingReview')catSyncMappingNames();var s=catSite(d.site),factory=s&&identityOrg(s.factory);if(a!=='catRemove'&&(!s||!s.active||s.factory!==d.factory||!factory.active)){identityError('请按名称选择启用工厂及其启用站点');return true;}d.remove=a==='catRemove';catDialog(d.remove?'确认解除承接关系':'确认承接变更','<p><b>'+esc(identityOrg(d.id).name)+'</b></p><p>'+esc(catRelation(d.id))+' → '+esc(d.remove?'未配置':factory.name+' / '+s.name)+'</p><p class="identity-alert">仅影响新订单，已有订单保持原承接对象和价格。'+(d.remove?'解除后可浏览选品，但不能下单。':'')+'</p>','catMappingCommit');}
    if(a==='catMappingCommit'){o=identityOrg(d.id);if(catChanged(o,d))return true;if(!d.remove){var targetSite=catSite(d.site);if(!targetSite||!targetSite.active||targetSite.factory!==d.factory||!identityOrg(targetSite.factory).active){identityError('承接工厂或站点状态已变化，请重新配置');return true;}}if(d.kind==='dispatch'){catalog.dispatched={factoryName:identityOrg(d.factory).name,siteName:catSite(d.site).name};catFinish('待派单订单已派发');return true;}if(d.remove)delete catalog.mappings[d.id];else catalog.mappings[d.id]=d.site;o.version++;catFinish('承接关系已保存，仅影响新订单');}
    return true;
  }
  function catShowFloors(){var h=catHotel(),floors=catFloors(h.id).filter(function(f){return f.active;});modalShell('选择所属楼层',h.name,'<p>切换仅改变本次归属，已选品类、数量、价格和额度均保留。</p><div class="catalog-floor-options">'+floors.map(function(f){return button(f.name,'catFloorPick:'+f.id,catalog.selection[h.id]===f.id?'primary-button':'secondary-button');}).join('')+'</div>',button('关闭','closeModal','secondary-button'));}
  function catOrderDetail(order){if(!order)return;var factoryView=roles[state.role].surface==='factory',displayAmount=factoryView?order.qty['被套']*5.5+order.qty['床单']*3.8+order.qty['浴巾']*1.9:order.total;modalShell('补充订单详情',order.id,'<dl class="identity-descriptions"><dt>酒店</dt><dd>'+esc(order.hotelName)+'</dd><dt>所属楼层</dt><dd>'+esc(order.floorName||'未指定')+'</dd><dt>配送地址</dt><dd>'+esc(order.address)+'</dd><dt>承接工厂 / 站点</dt><dd>'+esc(order.factoryName+' / '+order.siteName)+'</dd><dt>'+(factoryView?'工厂结算':'扣款金额')+'</dt><dd>'+money(displayAmount)+'</dd></dl><p>以上为下单时快照，档案及关系变更不改写历史订单。</p>'+table(['品类','数量'],Object.keys(order.qty).map(function(k){return[esc(k),order.qty[k]];})),button('关闭','closeModal','secondary-button'),true);}
  var baseIdentityRender=identityRender;identityRender=function(section){if(['酒店与楼层','洗涤厂与站点','酒店服务关系'].includes(section))return catList(section);return baseIdentityRender(section);};
  var baseIdentityHandle=identityHandle;identityHandle=function(action){var result=baseIdentityHandle(action);if(action==='identityOrgCommit'&&!modal.classList.contains('show')){var newest=identity.orgs[identity.orgs.length-1];newest.active=true;newest.version=1;if(newest.type==='factory')catalog.sites.push({id:'site-new-'+catalog.next++,factory:newest.id,name:newest.site,area:newest.area,address:newest.address,active:true,version:1});catalog.detail=newest.id;identity.detail='';state.section=newest.type==='hotel'?'酒店与楼层':'洗涤厂与站点';catalogSave();render();}return result;};
  var baseMobileReplenish=mobileReplenish;mobileReplenish=function(role){var h=catHotel(),floors=catFloors(h.id).filter(function(f){return f.active;});if(!Object.prototype.hasOwnProperty.call(catalog.selection,h.id)||(catalog.selection[h.id]===null&&floors.length)){catalog.selection[h.id]=floors.length?floors[0].id:null;catalogSave();}var chosen=catalog.floors.find(function(f){return f.id===catalog.selection[h.id]&&f.hotel===h.id&&f.active;}),invalid=catalog.selection[h.id]&&!chosen,html=baseMobileReplenish(Object.assign({},role,{org:h.name}));html=html.replace(/<div class="floor-row">[\s\S]*?<\/div>/,'<div class="catalog-demo"><label>演示酒店 <select data-cat-hotel aria-label="演示酒店">'+identity.orgs.filter(function(o){return o.type==='hotel';}).map(function(o){return '<option value="'+o.id+'"'+(h.id===o.id?' selected':'')+'>'+esc(o.name)+'</option>';}).join('')+'</select></label><small>与平台档案同步 · 本地演示</small></div>'+(floors.length?'<div class="floor-row"><span><small>所属楼层</small><strong>'+esc(chosen?chosen.name:'请选择有效楼层')+'</strong></span><button data-action="catChooseFloor">切换楼层 ›</button></div>':'')+(invalid?'<p class="identity-alert warning">原选楼层已停用，选品内容已保留，提交前请刷新选择。</p>':'')+(!catalog.mappings[h.id]?'<p class="identity-alert warning">尚未配置承接站点，可选品但暂不能下单。</p>':'')+(!h.active?'<p class="identity-alert warning">酒店已停用，暂不能提交新订单。</p>':''));return html;};
  showSubmitOrder=function(){var h=catHotel(),floors=catFloors(h.id).filter(function(f){return f.active;}),f=floors.find(function(f){return f.id===catalog.selection[h.id];}),s=catSite(catalog.mappings[h.id]);if(!h.active||!s||!s.active||!identityOrg(s.factory).active){showToast(!h.active?'酒店已停用，不能新增订单':'承接关系不可用，请联系平台配置');return;}if(!f&&(floors.length||catalog.selection[h.id])){modalShell('所属楼层已变化',h.name,'<p>已保留全部品类和数量。'+(floors.length?'请重新选择有效楼层。':'当前已无启用楼层，确认后可按未指定楼层提交。')+'</p>',button('返回修改','closeModal','secondary-button')+button(floors.length?'刷新选择':'确认无楼层提交',floors.length?'catChooseFloor':'catConfirmNoFloor','primary-button'));return;}var total=state.qty['被套']*8+state.qty['床单']*5.5+state.qty['浴巾']*2.8;modalShell('确认补充订单',h.name,'<div class="confirm-amount"><small>本次预计扣款</small><strong>'+money(total)+'</strong></div><p>所属楼层：'+esc(f?f.name:'未指定')+'</p><p>配送地址：'+esc(h.address)+'</p><p>承接：'+esc(catRelation(h.id))+'</p><p>提交时再次校验有效楼层、价格、额度和余额。</p>',button('返回修改','closeModal','secondary-button')+button('确认并扣款','catSubmitOrder','lime-button'));};
  var baseCatHandle=catHandle;catHandle=function(action){if(action==='catSubmitOrder'){if(!Object.values(state.qty).some(function(q){return Number.isSafeInteger(q)&&q>0;})){showToast('请至少选择一件布草');return true;}var h=catHotel(),s=catSite(catalog.mappings[h.id]),f=catFloors(h.id).find(function(f){return f.active&&f.id===catalog.selection[h.id];});if(!h.active||!s||!s.active||!identityOrg(s.factory).active||(!f&&(catFloors(h.id).some(function(f){return f.active;})||catalog.selection[h.id]))){showSubmitOrder();return true;}var order={id:'RP-DEMO-'+Date.now(),hotel:h.id,hotelName:h.name,floorName:f?f.name:null,address:h.address,factory:s.factory,site:s.id,factoryName:identityOrg(s.factory).name,siteName:s.name,qty:Object.assign({},state.qty),total:state.qty['被套']*8+state.qty['床单']*5.5+state.qty['浴巾']*2.8};catalog.orders.unshift(order);state.qty={'被套':0,'床单':0,'浴巾':0};catalogSave();closeModal();state.section='订单';render();catOrderDetail(order);return true;}return baseCatHandle(action);};
  var baseMobileOrders=mobileOrders;mobileOrders=function(role){var html=baseMobileOrders(role);if(mobileOrderTab==='orders')html=html.replace('<div class="order-card">',catalog.orders.filter(function(o){return o.hotel===catHotel().id;}).map(function(o){return '<div class="order-card"><header><span><strong>'+esc(o.id)+'</strong><small>所属楼层 '+esc(o.floorName||'未指定')+'</small></span>'+badge('已派单','')+'</header><p>'+esc(o.address)+'</p><footer><b>'+money(o.total)+'</b>'+button('查看详情','catOrder:'+o.id,'secondary-button')+'</footer></div>';}).join('')+'<div class="order-card">');return html;};
  showDispatchOrder=function(){catMappingDialog('org-hotel-full',true);};
  var baseActualOrders=actualOrders;actualOrders=function(role){var html=baseActualOrders(role),factory=role.surface==='factory';if(catalog.dispatched)html=html.replace(/<tr>(?:(?!<tr>)[\s\S])*?RP202609070012[\s\S]*?<\/tr>/,function(row){return row.replace('<button class="link-button" data-action="dispatchOrder">派单</button>','已派单').replace(badge('待派单','warning'),badge('已派单','')).replace('<td>—</td>','<td>'+esc(catalog.dispatched.factoryName)+'</td>');});var rows=catalog.orders.filter(function(o){return !factory||o.factory==='org-factory-1';}).map(function(o){var count=Object.values(o.qty).reduce(function(a,b){return a+b;},0),cost=o.qty['被套']*5.5+o.qty['床单']*3.8+o.qty['浴巾']*1.9,cells=factory?[esc(o.id),esc(o.hotelName),esc(o.floorName||'未指定'),count,money(cost),badge('已派单',''),'本次演示',button('详情','catOrder:'+o.id,'link-button')]:[esc(o.id),esc(o.hotelName),esc(o.floorName||'未指定'),count,money(o.total),money(cost),money(o.total-cost),esc(o.factoryName),badge('已派单',''),'本次演示',button('详情','catOrder:'+o.id,'link-button')];return '<tr>'+cells.map(function(c){return '<td>'+c+'</td>';}).join('')+'</tr>';}).join('');return html.replace('<tbody>','<tbody>'+rows);};
  var baseTerminal=terminalWorkspace;terminalWorkspace=function(role){var html=baseTerminal(role),own=catalog.sites.filter(function(s){return s.factory==='org-factory-1';});return html.replace(/<label><span>洗涤站点 ID<\/span>[\s\S]*?<\/label>/,'<label><span>洗涤站点</span><select data-terminal-field="site" aria-label="洗涤站点"><option value="">请选择本站点</option>'+own.map(function(s){return '<option value="'+s.id+'"'+(terminalDraft.site===s.id?' selected':'')+'>'+esc(s.name)+(s.active?'':'（停用，仅旧单备货）')+'</option>';}).join('')+'</select></label><p class="catalog-terminal-note">停用站点仅可处理已有本站未完成订单的租赁备货。演示旧单：RP202609070018（东区站）。</p>');};
  var baseSubmitTerminal=submitTerminal;submitTerminal=function(){var s=catSite(terminalDraft.site);if(!s||s.factory!=='org-factory-1'){showToast('请选择本工厂权限内的站点');return;}if(!s.active||!identityOrg(s.factory).active){var existing=(terminalDraft.reference==='RP202609070018'&&s.id==='site-factory-east'&&state.progress<3)||catalog.orders.some(function(o){return o.id===terminalDraft.reference&&o.site===s.id;});if(state.section!=='租赁备货'||!existing){showToast('停用站点仅允许本站已有未完成订单的租赁备货');return;}}baseSubmitTerminal();};
  root.addEventListener('change',function(e){if(e.target.hasAttribute('data-cat-hotel')){catalogSave();catalog.hotel=e.target.value;state.qty=Object.assign({'被套':0,'床单':0,'浴巾':0},catalog.drafts[catalog.hotel]||{});catalogSave();render();}if(e.target.dataset.terminalField)terminalDraft[e.target.dataset.terminalField]=e.target.value;});
  function catSyncMappingNames(changedKey){var d=catalog.draft;if(!d||!['mapping','dispatch'].includes(d.kind))return;var factoryInput=modal.querySelector('[data-cat-name="factory"]'),siteInput=modal.querySelector('[data-cat-name="site"]');if(!factoryInput||!siteInput)return;var selectedFactory=identity.orgs.find(function(o){return o.type==='factory'&&o.active&&o.name===factoryInput.value.trim();}),factoryId=selectedFactory?selectedFactory.id:'';if(factoryId!==d.factory){d.factory=factoryId;d.site='';siteInput.value='';}var sites=catalog.sites.filter(function(s){return s.factory===d.factory&&s.active;}),list=modal.querySelector('#cat-site');if(list)list.innerHTML=sites.map(function(s){return '<option value="'+esc(s.name)+'"></option>';}).join('');var selectedSite=sites.find(function(s){return s.name===siteInput.value.trim();});d.site=selectedSite?selectedSite.id:'';if(changedKey){var error=modal.querySelector('.identity-error');if(error)error.textContent='';}}
  modal.addEventListener('input',function(e){if(e.target.dataset.catName)catSyncMappingNames(e.target.dataset.catName);});
  modal.addEventListener('change',function(e){if(e.target.dataset.catName)catSyncMappingNames(e.target.dataset.catName);});
  window.addEventListener('beforeunload',catalogSave);

  function render(){
    var role=roles[state.role];
    root.innerHTML=role.surface==='mobile'?renderMobile(role):role.surface==='terminal'?renderTerminal(role):renderWeb(role);
    var url=new URL(location.href);url.searchParams.set('role',state.role);history.replaceState(null,'',url.toString());
  }
  function setRole(key){if(!roles[key])return;closeModal();identity.detail='';catalog.detail='';identity.queryDraft=null;identity.page=1;identity.query={q:'',org:'',role:'',status:'',type:''};state.role=key;state.section=roles[key].nav[0];state.view='normal';viewSelect.value='normal';render();}
  function showToast(message,tone){var el=document.getElementById('prototypeToast');el.textContent=message;el.className='prototype-toast show '+(tone||'');clearTimeout(toastTimer);toastTimer=setTimeout(function(){el.className='prototype-toast';},2400);}
  function handleClick(event){
    var userMenu=document.getElementById('webUserMenu');
    if(userMenu&&!event.target.closest('.user-menu-wrap'))userMenu.classList.remove('show');
    var section=event.target.closest('[data-section]');if(section){state.section=section.dataset.section;identity.detail='';catalog.detail='';identity.queryDraft=null;identity.page=1;identity.query={q:'',org:'',role:'',status:'',type:''};render();return;}
    var actionEl=event.target.closest('[data-action]');if(!actionEl)return;var action=actionEl.dataset.action;
    if(catHandle(action))return;
    if(action==='identityBackdrop'&&event.target.closest('.identity-drawer'))return;if(identityHandle(action))return;
    if(action==='userMenu'){var trigger=actionEl,menu=document.getElementById('webUserMenu'),open=!menu.classList.contains('show');menu.classList.toggle('show',open);trigger.setAttribute('aria-expanded',String(open));return;}
    if(action==='signOut'){showToast('已打开退出登录操作');return;}
    if(action==='collapseNav'){state.navCollapsed=!state.navCollapsed;render();return;}
    if(action==='openAccount'){state.section='账户';render();return;}
    if(action==='openEmployees'){state.section='员工';render();return;}
    if(action==='mobileRecords'){if(state.role==='hotel_admin'){state.section='账户';render();}else{showToast('请联系酒店管理员查看账户记录');}return;}
    if(action==='denied'){showToast('当前账号无此权限');return;}
    if(action==='back'){if(roles[state.role].surface==='mobile'){state.section=state.role==='driver'?'负责酒店':'我的';render();}else{closeModal();}return;}
    if(action==='closeModal'){closeModal();return;}
    if(action==='restore'){state.view='normal';viewSelect.value='normal';render();return;}
    if(action==='plus'||action==='minus'){var item=actionEl.dataset.item,max=Number(actionEl.dataset.max||999),delta=action==='plus'?1:-1;state.qty[item]=Math.max(0,Math.min(max,(state.qty[item]||0)+delta));catalogSave();render();return;}
    if(action==='advance'){state.progress=Math.min(3,state.progress+1);closeModal();render();showToast(['','订单已开始备货','订单已确认出库','订单已确认送达'][state.progress],'success');return;}
    if(action==='rejectRefund'){modalShell('确认驳回申请','RF202609070003',formRow('驳回原因',''),button('取消','closeModal','secondary-button')+button('确认驳回','confirmRejectRefund','primary-button'));return;}
    if(action==='confirmRefund'){var quantityInput=document.getElementById('refundQuantity'),quantity=Number(quantityInput&&quantityInput.value);if(!Number.isInteger(quantity)||quantity<1||quantity>5){showToast('数量须为 1 至 5 的整数');return;}}
    if(action==='confirmRejectRefund'){var reason=modal.querySelector('input');if(!reason||!reason.value.trim()){showToast('请填写驳回原因');return;}}
    if(action==='toggleCreatePassword'){var passwordInputs=modal.querySelectorAll('[data-create-password],[data-confirm-password]'),show=passwordInputs[0].type==='password';passwordInputs.forEach(function(input){input.type=show?'text':'password';});event.target.textContent=show?'隐藏密码':'显示密码';event.target.setAttribute('aria-pressed',String(show));return;}
    if(action==='confirmGeneric'&&modal.querySelector('[data-create-password]')){var initial=modal.querySelector('[data-create-password]'),confirmation=modal.querySelector('[data-confirm-password]'),error=passwordError(initial.value)||(!confirmation.value?'请再次输入初始密码':initial.value!==confirmation.value?'两次输入的密码不一致':'');modal.querySelector('.password-error').textContent=error;if(error){(passwordError(initial.value)?initial:confirmation).focus();return;}}
    if(/^confirm/.test(action)){var createdAccount=!!modal.querySelector('[data-create-password]');closeModal();showToast(createdAccount?'账号创建成功，请通过安全渠道告知使用者初始密码':action==='confirmOrder'?'订单 RP202609070019 已生成，已扣款 '+money(state.qty['被套']*8+state.qty['床单']*5.5+state.qty['浴巾']*2.8):action==='confirmRecharge'?'充值已登记，资金流水已生成':action==='confirmRefund'?'退污结果已提交，退款将按通过数量处理':action==='confirmDispatch'?'订单已派发至指定洗涤厂站点':action==='confirmRejectRefund'?'已驳回申请':'操作已完成','success');return;}
    if(action==='ordersTab'||action==='refundsTab'||action==='openRefunds'){mobileOrderTab=action==='ordersTab'?'orders':'refunds';state.section='订单';render();return;}
    if(action==='terminalSubmit'){submitTerminal();return;}
    if(action==='filter'||action==='resetFilters'){var controls=root.querySelectorAll('.filter-bar input,.filter-bar select');if(action==='resetFilters')controls.forEach(function(control){if(control.tagName==='SELECT')control.selectedIndex=0;else control.value='';});var selected=root.querySelector('.filter-bar select'),term=selected?selected.value:'';root.querySelectorAll('.data-table tbody tr').forEach(function(row){row.hidden=!!term&&term.indexOf('全部')!==0&&row.textContent.indexOf(term)<0;});showToast(action==='filter'?'已按当前条件查询':'筛选条件已重置');return;}
    if(action==='filter'||action==='resetFilters'||action==='export'||action==='notice'||action==='addCart'||action==='soldOut'){showToast(action==='filter'?'已按当前条件刷新':action==='resetFilters'?'筛选条件已重置':action==='export'?'已生成导出任务':action==='notice'?'暂无未读业务消息':action==='addCart'?'已加入订单':'当前商品库存为 0');return;}
    openForAction(action);
  }

  function inline(text){return esc(text).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>');}
  function parseMarkdown(md){
    var lines=md.replace(/\r/g,'').split('\n'),html=[],heads=[],i=0,lists=[];
    function closeList(){var list=lists.pop();html.push('</li></'+list.tag+'>');}
    function closeLists(){while(lists.length)closeList();}
    while(i<lines.length){
      var line=lines[i],trim=line.trim();
      if(!trim){i++;continue;}
      if(/^---+$/.test(trim)){closeLists();html.push('<hr>');i++;continue;}
      var heading=/^(#{1,4})\s+(.+)$/.exec(trim);
      if(heading){closeLists();var level=heading[1].length,id='prd-'+heads.length;heads.push({id:id,level:level,text:heading[2]});html.push('<h'+level+' id="'+id+'">'+inline(heading[2])+'</h'+level+'>');i++;continue;}
      if(trim.indexOf('|')===0&&i+1<lines.length&&/^\s*\|?[\s:|-]+\|\s*$/.test(lines[i+1])){closeLists();var rows=[],j=i;while(j<lines.length&&lines[j].trim().indexOf('|')===0){rows.push(lines[j].trim().replace(/^\||\|$/g,'').split('|').map(function(cell){return cell.trim();}));j++;}html.push('<table><thead><tr>'+rows[0].map(function(cell){return '<th>'+inline(cell)+'</th>';}).join('')+'</tr></thead><tbody>'+rows.slice(2).map(function(row){return '<tr>'+row.map(function(cell){return '<td>'+inline(cell)+'</td>';}).join('')+'</tr>';}).join('')+'</tbody></table>');i=j;continue;}
      var numbered=/^\d+\.\s+(.+)$/.exec(trim),item=/^[-*]\s+(.+)$/.exec(trim);
      if(numbered||item){var indent=line.match(/^\s*/)[0].length,tag=numbered?'ol':'ul';while(lists.length&&indent<lists[lists.length-1].indent)closeList();if(lists.length&&indent===lists[lists.length-1].indent&&tag!==lists[lists.length-1].tag)closeList();if(!lists.length||indent>lists[lists.length-1].indent){html.push('<'+tag+'>');lists.push({indent:indent,tag:tag});}else html.push('</li>');html.push('<li>'+inline((numbered||item)[1]));i++;continue;}
      closeLists();html.push('<p>'+inline(trim)+'</p>');i++;
    }
    closeLists();return {html:html.join(''),heads:heads};
  }
  function initPrd(){var md=document.getElementById('prdMdSource').textContent.replace(/^\n/,'');var parsed=parseMarkdown(md);document.getElementById('prdContent').innerHTML=parsed.html;document.getElementById('prdToc').innerHTML='<div class="prd-toc-title">产品需求目录</div>'+parsed.heads.filter(function(h){return h.level>1&&h.level<4;}).map(function(h){return '<button class="prd-toc-item level-'+h.level+'" data-prd-target="'+h.id+'">'+esc(h.text)+'</button>';}).join('');}
  function initDrag(){var drag=document.getElementById('splitDrag'),panel=document.getElementById('prdPanel'),startX=0,startW=0;drag.addEventListener('mousedown',function(event){if(panel.classList.contains('collapsed'))return;event.preventDefault();startX=event.clientX;startW=panel.offsetWidth;drag.classList.add('dragging');document.body.style.cursor='col-resize';document.body.style.userSelect='none';function move(e){panel.style.width=Math.max(330,Math.min(Math.floor(innerWidth*.72),startW-(e.clientX-startX)))+'px';}function up(){drag.classList.remove('dragging');document.body.style.cursor='';document.body.style.userSelect='';document.removeEventListener('mousemove',move);document.removeEventListener('mouseup',up);}document.addEventListener('mousemove',move);document.addEventListener('mouseup',up);});}
  function togglePrd(){var panel=document.getElementById('prdPanel'),button=document.getElementById('prdToggle');panel.classList.toggle('collapsed');button.textContent=panel.classList.contains('collapsed')?'展开 PRD':'收起 PRD';}
  function downloadPrd(){var blob=new Blob([document.getElementById('prdMdSource').textContent.replace(/^\n/,'')],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='优洗通当前系统产品需求文档.md';a.click();setTimeout(function(){URL.revokeObjectURL(url);},0);}
  function showChangelog(){var mask=document.getElementById('changelogMask'),items=typeof changelogData==='undefined'?[]:changelogData;document.getElementById('changelogBody').innerHTML=items.map(function(item){return '<div class="release-item"><b>'+esc(item.time)+'</b><p>'+esc(item.desc)+'</p></div>';}).join('');mask.classList.add('show');mask.setAttribute('aria-hidden','false');}
  function closeChangelog(){var mask=document.getElementById('changelogMask');mask.classList.remove('show');mask.setAttribute('aria-hidden','true');}

  modal.addEventListener('change',function(e){if(!identity.draft)return;if(identity.draft.kind==='org'){if(e.target.dataset.identityField==='type'){identityCapture();identity.draft.role=identity.draft.type+'_admin';identityDrawOrg();}return;}if(e.target.dataset.identityField==='orgSearch'){identityCapture();var selected=identity.orgs.find(function(o){return o.name===e.target.value&&identityAssignable(o.id).some(function(r){return !identity.draft.driverOnly||r==='driver';});});identity.draft.org=selected?selected.id:'';identity.draft.role='';identity.draft.hotels=[];identityDrawMember();if(!selected)identityError('请从列表选择有效组织');}else if(e.target.dataset.identityField==='role'||e.target.dataset.identityField==='mode'){identityCapture();identityDrawMember();}});
  function identityRememberFilters(e){var scope=e.target.closest('.identity-filter');if(!scope)return;var values={q:'',org:'',role:'',status:'',type:''};scope.querySelectorAll('[data-identity-field]').forEach(function(el){if(el.dataset.identityField==='orgSearch'){var found=identity.orgs.find(function(o){return o.name===el.value;});values.org=found?found.id:'';}else values[el.dataset.identityField]=el.value;});if(scope.dataset.filterScope==='organizations')identity.orgQueryDraft=values;else identity.queryDraft=values;}
  root.addEventListener('input',identityRememberFilters);root.addEventListener('change',identityRememberFilters);
  root.addEventListener('submit',function(e){if(e.target.matches('.identity-filter')){e.preventDefault();identityHandle('identitySearch');}});
  roleSelect.addEventListener('change',function(){setRole(this.value);});
  viewSelect.addEventListener('change',function(){state.view=this.value;render();});
  root.addEventListener('click',handleClick);modal.addEventListener('click',handleClick);modal.addEventListener('click',function(e){if(e.target===this)closeModal();});
  root.addEventListener('input',function(e){var key=e.target.dataset.terminalField;if(key&&Object.prototype.hasOwnProperty.call(terminalDraft,key))terminalDraft[key]=e.target.value;});
  document.getElementById('prdToggle').addEventListener('click',togglePrd);document.getElementById('downloadPrdBtn').addEventListener('click',downloadPrd);document.getElementById('changelogBtn').addEventListener('click',showChangelog);document.getElementById('closeChangelog').addEventListener('click',closeChangelog);document.getElementById('changelogMask').addEventListener('click',function(e){if(e.target===this)closeChangelog();});
  document.getElementById('prdToc').addEventListener('click',function(e){var buttonEl=e.target.closest('[data-prd-target]');if(!buttonEl)return;var target=document.getElementById(buttonEl.dataset.prdTarget);if(target){var content=document.getElementById('prdContent');content.scrollTop+=target.getBoundingClientRect().top-content.getBoundingClientRect().top;}});
  document.addEventListener('keydown',function(e){if(e.key==='Escape'){if(modal.classList.contains('show')){if(modal.querySelector('[data-action="identityReturn"]'))identityDrawMember();else closeModal();}else if(identity.detail){identity.detail='';render();}closeChangelog();}});
  document.addEventListener('DOMContentLoaded',function(){var initial=new URL(location.href).searchParams.get('role');if(initial&&roles[initial])state.role=initial;state.section=roles[state.role].nav[0];roleSelect.innerHTML=Object.keys(roles).map(function(key){return '<option value="'+key+'">'+esc(roles[key].label)+'</option>';}).join('');roleSelect.value=state.role;viewSelect.value=state.view;initPrd();initDrag();render();});
})();
